### ISSUE TITLE
AWS CLI connectivity issue: Windows client to remote Scality

### ISSUE THREAD

**Issue by dunedinsoftware** [scality/S3#1115]
### Description
aws s3 ls --endpoint-url=http://linux_box:8000 --debug

Falls back on SSL authentication and fails; should authenticate with HTTP

### Steps to reproduce the issue
Follow standard set up documentation for a CentOS client
Then attempt to connect to said client via Windows AWS CLI as above
Note that "local" connectivity between Linux box and Scality is fine.
Note that curl, etc. return valid response (not a firewall issue)

Output:

l.s3.ListBuckets: calling handler <function add_expect_header at 0x000000000312D
6D8>
2018-02-08 16:43:09,601 - MainThread - botocore.hooks - DEBUG - Event before-cal
l.s3.ListBuckets: calling handler <bound method S3RegionRedirector.set_request_u
rl of <botocore.utils.S3RegionRedirector object at 0x0000000004296DD8>>
2018-02-08 16:43:09,601 - MainThread - botocore.endpoint - DEBUG - Making reques
t for OperationModel(name=ListBuckets) (verify_ssl=True) with params: {'body': '
', 'url': u'http://ut008693:8000/', 'headers': {'User-Agent': 'aws-cli/1.14.22 P
ython/2.7.9 Windows/7 botocore/1.8.26'}, 'context': {'auth_type': None, 'client_
region': 'us-east-1', 'signing': {'bucket': None}, 'has_streaming_input': False,
 'client_config': <botocore.config.Config object at 0x0000000004296048>}, 'query
_string': '', 'url_path': u'/', 'method': u'GET'}
2018-02-08 16:43:09,601 - MainThread - botocore.hooks - DEBUG - Event request-cr
eated.s3.ListBuckets: calling handler <bound method RequestSigner.handler of <bo
tocore.signers.RequestSigner object at 0x000000000428AF98>>
2018-02-08 16:43:09,601 - MainThread - botocore.hooks - DEBUG - Event choose-sig
ner.s3.ListBuckets: calling handler <bound method ClientCreator._default_s3_pres
ign_to_sigv2 of <botocore.client.ClientCreator object at 0x0000000003FF2780>>
2018-02-08 16:43:09,601 - MainThread - botocore.hooks - DEBUG - Event choose-sig
ner.s3.ListBuckets: calling handler <function set_operation_specific_signer at 0
x0000000003126EB8>
2018-02-08 16:43:09,602 - MainThread - botocore.auth - DEBUG - Calculating signa
ture using v4 auth.
2018-02-08 16:43:09,602 - MainThread - botocore.auth - DEBUG - CanonicalRequest:

GET
/

host:ut008693:8000
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b785
2b855
x-amz-date:20180208T164309Z

host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2018-02-08 16:43:09,604 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20180208T164309Z
20180208/us-east-1/s3/aws4_request
27c612558e8c3e70cc8adebff41ff6f869f570ebebecaea665787120d725b82c
2018-02-08 16:43:09,604 - MainThread - botocore.auth - DEBUG - Signature:
ea8b883a19c7ad42345bb70595f1e8827d1109e1cac85913fa0e21f5cd3f1b5c
2018-02-08 16:43:09,608 - MainThread - botocore.endpoint - DEBUG - Sending http
request: <PreparedRequest [GET]>
2018-02-08 16:43:09,608 - MainThread - botocore.vendored.requests.packages.urlli
b3.connectionpool - INFO - Starting new HTTP connection (1): ut008693
2018-02-08 16:43:09,648 - MainThread - botocore.vendored.requests.packages.urlli
b3.connectionpool - DEBUG - "GET / HTTP/1.1" 400 233
2018-02-08 16:43:09,651 - MainThread - botocore.parsers - DEBUG - Response heade
rs: {'content-length': '233', 'x-amz-id-2': '8538fda9a648a5b77e82', 'server': 'S
3 Server', 'connection': 'keep-alive', 'x-amz-request-id': '8538fda9a648a5b77e82
', 'date': 'Thu, 08 Feb 2018 16:43:09 GMT', 'content-type': 'application/xml'}
2018-02-08 16:43:09,651 - MainThread - botocore.parsers - DEBUG - Response body:

<?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidURI</Code><Message>Cou
ld not parse the specified URI. Check your restEndpoints configuration.</Message
><Resource></Resource><RequestId>8538fda9a648a5b77e82</RequestId></Error>
2018-02-08 16:43:09,653 - MainThread - botocore.hooks - DEBUG - Event needs-retr
y.s3.ListBuckets: calling handler <botocore.retryhandler.RetryHandler object at
0x0000000004296DA0>
2018-02-08 16:43:09,654 - MainThread - botocore.retryhandler - DEBUG - No retry
needed.
2018-02-08 16:43:09,654 - MainThread - botocore.hooks - DEBUG - Event needs-retr
y.s3.ListBuckets: calling handler <bound method S3RegionRedirector.redirect_from
_error of <botocore.utils.S3RegionRedirector object at 0x0000000004296DD8>>
2018-02-08 16:43:09,655 - MainThread - botocore.hooks - DEBUG - Event after-call
.s3.ListBuckets: calling handler <function enhance_error_msg at 0x0000000003EA1D
D8>
2018-02-08 16:43:09,665 - MainThread - awscli.clidriver - DEBUG - Exception caug
ht in main()
Traceback (most recent call last):
  File "awscli\clidriver.pyc", line 207, in main
  File "awscli\customizations\commands.pyc", line 190, in __call__
  File "awscli\customizations\commands.pyc", line 187, in __call__
  File "awscli\customizations\s3\subcommands.pyc", line 475, in _run_main
  File "awscli\customizations\s3\subcommands.pyc", line 540, in _list_all_bucket
s
  File "botocore\client.pyc", line 317, in _api_call
  File "botocore\client.pyc", line 615, in _make_api_call
ClientError: An error occurred (InvalidURI) when calling the ListBuckets operati
on: Could not parse the specified URI. Check your restEndpoints configuration.
2018-02-08 16:43:09,667 - MainThread - awscli.clidriver - DEBUG - Exiting with r
c 255

An error occurred (InvalidURI) when calling the ListBuckets operation: Could not
 parse the specified URI. Check your restEndpoints configuration.

C:\Users\ahi17\.aws>notepad dump.txt

C:\Users\ahi17\.aws>aws s3 ls --endpoint-url=http://ut008693:8000 --debug > dump
.txt
2018-02-08 16:47:42,578 - MainThread - awscli.clidriver - DEBUG - CLI version: a
ws-cli/1.14.22 Python/2.7.9 Windows/7 botocore/1.8.26
2018-02-08 16:47:42,579 - MainThread - awscli.clidriver - DEBUG - Arguments ente
red to CLI: ['s3', 'ls', '--endpoint-url=http://ut008693:8000', '--debug']
2018-02-08 16:47:42,581 - MainThread - botocore.hooks - DEBUG - Event session-in
itialized: calling handler <function add_scalar_parsers at 0x0000000003E7E208>
2018-02-08 16:47:42,581 - MainThread - botocore.session - DEBUG - Loading variab
le profile from defaults.
2018-02-08 16:47:42,581 - MainThread - botocore.hooks - DEBUG - Event session-in
itialized: calling handler <function inject_assume_role_provider_cache at 0x0000
0000036D1CF8>
2018-02-08 16:47:42,581 - MainThread - botocore.session - DEBUG - Loading variab
le profile from defaults.
2018-02-08 16:47:42,582 - MainThread - botocore.session - DEBUG - Loading variab
le credentials_file from defaults.
2018-02-08 16:47:42,582 - MainThread - botocore.session - DEBUG - Loading variab
le config_file from defaults.
2018-02-08 16:47:42,582 - MainThread - botocore.session - DEBUG - Loading variab
le profile from defaults.
2018-02-08 16:47:42,582 - MainThread - botocore.session - DEBUG - Loading variab
le metadata_service_timeout from defaults.
2018-02-08 16:47:42,582 - MainThread - botocore.session - DEBUG - Loading variab
le profile from defaults.
2018-02-08 16:47:42,582 - MainThread - botocore.session - DEBUG - Loading variab
le metadata_service_num_attempts from defaults.
2018-02-08 16:47:42,582 - MainThread - botocore.session - DEBUG - Loading variab
le profile from defaults.
2018-02-08 16:47:42,582 - MainThread - botocore.hooks - DEBUG - Event session-in
itialized: calling handler <function attach_history_handler at 0x0000000003CF93C
8>
2018-02-08 16:47:42,584 - MainThread - botocore.session - DEBUG - Loading variab
le profile from defaults.
2018-02-08 16:47:42,584 - MainThread - botocore.hooks - DEBUG - Event building-c
ommand-table.s3: calling handler <function add_waiters at 0x0000000003E85198>
2018-02-08 16:47:42,585 - MainThread - botocore.hooks - DEBUG - Event load-cli-a
rg.custom.s3.anonymous: calling handler <function uri_param at 0x00000000033A582
8>
2018-02-08 16:47:42,585 - MainThread - botocore.hooks - DEBUG - Event building-c
ommand-table.ls: calling handler <function add_waiters at 0x0000000003E85198>
2018-02-08 16:47:42,585 - MainThread - botocore.hooks - DEBUG - Event load-cli-a
rg.custom.ls.paths: calling handler <function uri_param at 0x00000000033A5828>
2018-02-08 16:47:42,585 - MainThread - botocore.hooks - DEBUG - Event load-cli-a
rg.custom.ls.human-readable: calling handler <function uri_param at 0x0000000003
3A5828>
2018-02-08 16:47:42,586 - MainThread - botocore.hooks - DEBUG - Event process-cl
i-arg.custom.ls: calling handler <awscli.argprocess.ParamShorthandParser object
at 0x00000000036ADE80>
2018-02-08 16:47:42,586 - MainThread - botocore.hooks - DEBUG - Event load-cli-a
rg.custom.ls.page-size: calling handler <function uri_param at 0x00000000033A582
8>
2018-02-08 16:47:42,586 - MainThread - botocore.hooks - DEBUG - Event load-cli-a
rg.custom.ls.anonymous: calling handler <function uri_param at 0x00000000033A582
8>
2018-02-08 16:47:42,586 - MainThread - botocore.hooks - DEBUG - Event load-cli-a
rg.custom.ls.request-payer: calling handler <function uri_param at 0x00000000033
A5828>
2018-02-08 16:47:42,588 - MainThread - botocore.hooks - DEBUG - Event load-cli-a
rg.custom.ls.summarize: calling handler <function uri_param at 0x00000000033A582
8>
2018-02-08 16:47:42,588 - MainThread - botocore.hooks - DEBUG - Event process-cl
i-arg.custom.ls: calling handler <awscli.argprocess.ParamShorthandParser object
at 0x00000000036ADE80>
2018-02-08 16:47:42,588 - MainThread - botocore.session - DEBUG - Loading variab
le profile from defaults.
2018-02-08 16:47:42,588 - MainThread - botocore.session - DEBUG - Loading variab
le profile from defaults.
2018-02-08 16:47:42,588 - MainThread - botocore.session - DEBUG - Loading variab
le region from config file with value 'us-east-1'.
2018-02-08 16:47:42,588 - MainThread - botocore.session - DEBUG - Loading variab
le profile from defaults.
2018-02-08 16:47:42,588 - MainThread - botocore.session - DEBUG - Loading variab
le ca_bundle from defaults.
2018-02-08 16:47:42,588 - MainThread - botocore.session - DEBUG - Loading variab
le profile from defaults.
2018-02-08 16:47:42,589 - MainThread - botocore.session - DEBUG - Loading variab
le api_versions from defaults.
2018-02-08 16:47:42,589 - MainThread - botocore.credentials - DEBUG - Looking fo
r credentials via: env
2018-02-08 16:47:42,589 - MainThread - botocore.credentials - DEBUG - Looking fo
r credentials via: assume-role
2018-02-08 16:47:42,589 - MainThread - botocore.credentials - DEBUG - Looking fo
r credentials via: shared-credentials-file
2018-02-08 16:47:42,591 - MainThread - botocore.credentials - INFO - Found crede
ntials in shared credentials file: ~/.aws/credentials
2018-02-08 16:47:42,592 - MainThread - botocore.loaders - DEBUG - Loading JSON f
ile: C:\Program Files\Amazon\AWSCLI\botocore\data\endpoints.json
2018-02-08 16:47:42,612 - MainThread - botocore.session - DEBUG - Loading variab
le profile from defaults.
2018-02-08 16:47:42,612 - MainThread - botocore.hooks - DEBUG - Event choose-ser
vice-name: calling handler <function handle_service_name_alias at 0x000000000310
0D68>
2018-02-08 16:47:42,615 - MainThread - botocore.loaders - DEBUG - Loading JSON f
ile: C:\Program Files\Amazon\AWSCLI\botocore\data\s3\2006-03-01\service-2.json
2018-02-08 16:47:42,654 - MainThread - botocore.hooks - DEBUG - Event creating-c
lient-class.s3: calling handler <function add_generate_presigned_post at 0x00000
000030D0CF8>
2018-02-08 16:47:42,654 - MainThread - botocore.hooks - DEBUG - Event creating-c
lient-class.s3: calling handler <function add_generate_presigned_url at 0x000000
00030D0B38>
2018-02-08 16:47:42,655 - MainThread - botocore.args - DEBUG - The s3 config key
 is not a dictionary type, ignoring its value of: None
2018-02-08 16:47:42,660 - MainThread - botocore.endpoint - DEBUG - Setting s3 ti
meout as (60, 60)
2018-02-08 16:47:42,661 - MainThread - botocore.client - DEBUG - Registering ret
ry handlers for service: s3
2018-02-08 16:47:42,661 - MainThread - botocore.client - DEBUG - Using S3 path s
tyle addressing.
2018-02-08 16:47:42,663 - MainThread - botocore.hooks - DEBUG - Event before-par
ameter-build.s3.ListBuckets: calling handler <function validate_bucket_name at 0
x00000000031172E8>
2018-02-08 16:47:42,663 - MainThread - botocore.hooks - DEBUG - Event before-par
ameter-build.s3.ListBuckets: calling handler <bound method S3RegionRedirector.re
direct_from_cache of <botocore.utils.S3RegionRedirector object at 0x000000000429
2DD8>>
2018-02-08 16:47:42,663 - MainThread - botocore.hooks - DEBUG - Event before-par
ameter-build.s3.ListBuckets: calling handler <function generate_idempotent_uuid
at 0x0000000003100F98>
2018-02-08 16:47:42,664 - MainThread - botocore.hooks - DEBUG - Event before-cal
l.s3.ListBuckets: calling handler <function add_expect_header at 0x0000000003117
6D8>
2018-02-08 16:47:42,664 - MainThread - botocore.hooks - DEBUG - Event before-cal
l.s3.ListBuckets: calling handler <bound method S3RegionRedirector.set_request_u
rl of <botocore.utils.S3RegionRedirector object at 0x0000000004292DD8>>
2018-02-08 16:47:42,664 - MainThread - botocore.endpoint - DEBUG - Making reques
t for OperationModel(name=ListBuckets) (verify_ssl=True) with params: {'body': '
', 'url': u'http://ut008693:8000/', 'headers': {'User-Agent': 'aws-cli/1.14.22 P
ython/2.7.9 Windows/7 botocore/1.8.26'}, 'context': {'auth_type': None, 'client_
region': 'us-east-1', 'signing': {'bucket': None}, 'has_streaming_input': False,
 'client_config': <botocore.config.Config object at 0x0000000004292048>}, 'query
_string': '', 'url_path': u'/', 'method': u'GET'}
2018-02-08 16:47:42,664 - MainThread - botocore.hooks - DEBUG - Event request-cr
eated.s3.ListBuckets: calling handler <bound method RequestSigner.handler of <bo
tocore.signers.RequestSigner object at 0x0000000004286F98>>
2018-02-08 16:47:42,664 - MainThread - botocore.hooks - DEBUG - Event choose-sig
ner.s3.ListBuckets: calling handler <bound method ClientCreator._default_s3_pres
ign_to_sigv2 of <botocore.client.ClientCreator object at 0x0000000003FF5780>>
2018-02-08 16:47:42,664 - MainThread - botocore.hooks - DEBUG - Event choose-sig
ner.s3.ListBuckets: calling handler <function set_operation_specific_signer at 0
x0000000003100EB8>
2018-02-08 16:47:42,665 - MainThread - botocore.auth - DEBUG - Calculating signa
ture using v4 auth.
2018-02-08 16:47:42,665 - MainThread - botocore.auth - DEBUG - CanonicalRequest:

GET
/

host:ut008693:8000
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b785
2b855
x-amz-date:20180208T164742Z

host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2018-02-08 16:47:42,667 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20180208T164742Z
20180208/us-east-1/s3/aws4_request
465a69ee0e0b528b6069e5ff271165592545d6b19cbfbb5b35ab7072a5fa816b
2018-02-08 16:47:42,667 - MainThread - botocore.auth - DEBUG - Signature:
94238c93cce93122c6ee314e932d281a6ec02a6d36d9547487a1a76be486936d
2018-02-08 16:47:42,671 - MainThread - botocore.endpoint - DEBUG - Sending http
request: <PreparedRequest [GET]>
2018-02-08 16:47:42,671 - MainThread - botocore.vendored.requests.packages.urlli
b3.connectionpool - INFO - Starting new HTTP connection (1): ut008693
2018-02-08 16:47:42,707 - MainThread - botocore.vendored.requests.packages.urlli
b3.connectionpool - DEBUG - "GET / HTTP/1.1" 400 233
2018-02-08 16:47:42,709 - MainThread - botocore.parsers - DEBUG - Response heade
rs: {'content-length': '233', 'x-amz-id-2': 'f02356fe4d41bb671a51', 'server': 'S
3 Server', 'connection': 'keep-alive', 'x-amz-request-id': 'f02356fe4d41bb671a51
', 'date': 'Thu, 08 Feb 2018 16:47:42 GMT', 'content-type': 'application/xml'}
2018-02-08 16:47:42,710 - MainThread - botocore.parsers - DEBUG - Response body:

<?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidURI</Code><Message>Cou
ld not parse the specified URI. Check your restEndpoints configuration.</Message
><Resource></Resource><RequestId>f02356fe4d41bb671a51</RequestId></Error>
2018-02-08 16:47:42,710 - MainThread - botocore.hooks - DEBUG - Event needs-retr
y.s3.ListBuckets: calling handler <botocore.retryhandler.RetryHandler object at
0x0000000004292DA0>
2018-02-08 16:47:42,710 - MainThread - botocore.retryhandler - DEBUG - No retry
needed.
2018-02-08 16:47:42,710 - MainThread - botocore.hooks - DEBUG - Event needs-retr
y.s3.ListBuckets: calling handler <bound method S3RegionRedirector.redirect_from
_error of <botocore.utils.S3RegionRedirector object at 0x0000000004292DD8>>
2018-02-08 16:47:42,710 - MainThread - botocore.hooks - DEBUG - Event after-call
.s3.ListBuckets: calling handler <function enhance_error_msg at 0x0000000003E7AD
D8>
2018-02-08 16:47:42,713 - MainThread - awscli.clidriver - DEBUG - Exception caug
ht in main()
Traceback (most recent call last):
  File "awscli\clidriver.pyc", line 207, in main
  File "awscli\customizations\commands.pyc", line 190, in __call__
  File "awscli\customizations\commands.pyc", line 187, in __call__
  File "awscli\customizations\s3\subcommands.pyc", line 475, in _run_main
  File "awscli\customizations\s3\subcommands.pyc", line 540, in _list_all_bucket
s
  File "botocore\client.pyc", line 317, in _api_call
  File "botocore\client.pyc", line 615, in _make_api_call
ClientError: An error occurred (InvalidURI) when calling the ListBuckets operati
on: Could not parse the specified URI. Check your restEndpoints configuration.
2018-02-08 16:47:42,714 - MainThread - awscli.clidriver - DEBUG - Exiting with r
c 255

An error occurred (InvalidURI) when calling the ListBuckets operation: Could not
 parse the specified URI. Check your restEndpoints configuration.

**Comment by nicolas2bert** [comment]
Adding `"linux_box": "us-east-1",` inside the "restEndpoints" section of your [config.json](https://github.com/scality/S3/blob/master/config.json#L5) should fix your issue.
