### ISSUE TITLE
Cannot find repo scality/cdmiclient

### ISSUE THREAD

**Issue by YannickFricke** [scality/S3#1150]
# Issue template

If you are reporting a new issue, make sure that we do not have any
duplicates already open. You can ensure this by searching the issue list for
this repository. If there is a duplicate, please close your issue and add a
comment to the existing issue instead.

## General support information

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should9.7.1 be sent to the
[S3 scality server Forum](http://forum.scality.com/).

### Description

While performing "npm install" he can't find the scality/cdmiclient repository

### Steps to reproduce the issue

Clone project from Github and run "npm install"

### Actual result

I'm getting the following error message:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cdmiclient@github:scality/cdmiclient (node_modules/cdmiclient):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error while executing:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: /usr/bin/git ls-remote -h -t ssh://git@github.com/scality/cdmiclient.git
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ERROR: Repository not found.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fatal: Could not read from remote repository.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Please make sure you have the correct access rights
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: and the repository exists.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: exited with error code: 128
npm WARN eslint-config-airbnb@6.2.0 requires a peer of eslint-plugin-react@^4.2.3 but none is installed. You must install peer dependencies yourself.
```

### Expected result

Performing a clean installation of all dependencies.

### Additional information: (Node.js version, Docker version, etc)
NPM Version: 5.7.1
Node Version: 9.7.1

**Comment by rahulreddy** [comment]
Hi @YannickFricke ,
`cdmiclient` is a Scality private module which is why it is configured as an optional dependency. It should not impact the server startup/usage as the default backend is installed correctly.

**Comment by YannickFricke** [comment]
Hi @rahulreddy,
as you see it impacts the installation of S3 :)

**Comment by LaureVergeron** [comment]
Hi @YannickFricke ,

The errors you're seeing are npm warnings, not npm failures. Have you starting the service (npm start) to check whether you could use it? I am confident the install went well, as Rahul said.
If you can't start it, can you send us the logs please, so we can look into them?

Cheers!

**Comment by YannickFricke** [comment]
Hi @LaureVergeron ,

you see it as warning, but actually it is an error.

Here is the log from npm while performing `npm start`

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v9.8.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle s3@7.4.0~prestart: s3@7.4.0
6 info lifecycle s3@7.4.0~start: s3@7.4.0
7 verbose lifecycle s3@7.4.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle s3@7.4.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/srv/S3/node_modules/.bin:/home/yfr/bin:/home/yfr/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/yfr/.composer/vendor/bin
9 verbose lifecycle s3@7.4.0~start: CWD: /srv/S3
10 silly lifecycle s3@7.4.0~start: Args: [ '-c', 'npm-run-all --parallel start_dmd start_s3server' ]
11 silly lifecycle s3@7.4.0~start: Returned: code: 1  signal: null
12 info lifecycle s3@7.4.0~start: Failed to exec start script
13 verbose stack Error: s3@7.4.0 start: `npm-run-all --parallel start_dmd start_s3server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid s3@7.4.0
15 verbose cwd /srv/S3
16 verbose Linux 4.13.0-37-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v9.8.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error s3@7.4.0 start: `npm-run-all --parallel start_dmd start_s3server`
22 error Exit status 1
23 error Failed at the s3@7.4.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Here is the error from the console:
```
yfr@yfr-linux /s/S3> npm start

> s3@7.4.0 start /srv/S3
> npm-run-all --parallel start_dmd start_s3server


> s3@7.4.0 start_s3server /srv/S3
> node index.js


> s3@7.4.0 start_dmd /srv/S3
> npm-run-all --parallel start_mdserver start_dataserver


> s3@7.4.0 start_mdserver /srv/S3
> node mdserver.js


> s3@7.4.0 start_dataserver /srv/S3
> node dataserver.js

/srv/S3/mdserver.js:8
    const mdServer = new MetadataFileServer(
                     ^

TypeError: MetadataFileServer is not a constructor
    at Object.<anonymous> (/srv/S3/mdserver.js:8:22)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! s3@7.4.0 start_mdserver: `node mdserver.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the s3@7.4.0 start_mdserver script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
{"name":"DataFileStore","time":1521178892623,"level":"info","message":"pre-creating 3511 subdirs...","hostname":"yfr-linux","pid":7542}

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yfr/.npm/_logs/2018-03-16T05_41_32_585Z-debug.log
ERROR: "start_mdserver" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! s3@7.4.0 start_dmd: `npm-run-all --parallel start_mdserver start_dataserver`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the s3@7.4.0 start_dmd script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yfr/.npm/_logs/2018-03-16T05_41_32_759Z-debug.log
ERROR: "start_dmd" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! s3@7.4.0 start: `npm-run-all --parallel start_dmd start_s3server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the s3@7.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yfr/.npm/_logs/2018-03-16T05_41_32_844Z-debug.log
```

Cheers!

**Comment by rahulreddy** [comment]
@YannickFricke ,
Thanks for the log output. The error is not actually because of that module not installing but incorrect version of code/dependencies. It's possible that your code is out of date, can you please rebase from master again and re-install npm modules?
One more thing, I noticed that you are using nodejs version `9.7.1`. We currently support `> 6.9.5`, please make sure you install the above version before installing the npm modules and starting the server.

**Comment by YannickFricke** [comment]
@rahulreddy 
Sorry for my very late reply!

Rebased code now I am on commit "208c024" and removed "node_modules" directory.
Still the same error: Git cannot read from the remote repository "ssh://git@github.com/scality/cdmiclient.git"

When I run git like it is showing in the output I get the following message:
```
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I tried to install the dependencies with yarn and with npm and get the error with both.

But as far as I know: It shouldn't depend on yarn / npm / node. It's a problem with git.

**Comment by sriramHaven** [comment]
@rahulreddy @LaureVergeron  I m seeing the errors wfor cdmiclient . I know its optional, but if its not found, why can we not remove from dependencies? and also can i ignore it not uninstalling?

```
MM99468M2:S3 mm99468$ sudo npm install
Password:
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/scality/cdmiclient.git
npm ERR! 
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128
```

**Comment by mincaeuro** [comment]
Hi got same problem:
`
npm install
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/scality/cdmiclient.git
npm ERR!
npm ERR! Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-07-03T19_58_45_058Z-debug.log`

**Comment by YannickFricke** [comment]
@rahulreddy @LaureVergeron 
Still no solution?

**Comment by rahulreddy** [comment]
@YannickFricke  I was unable to reproduce this, I am gonna be trying again with a non-scality Github user and get back to you.

**Comment by smaffulli** [comment]
I just tried `npm install` again from an anonymous github clone. The install doesn't seem to fail, although the error is thrown. But the current version fails to start (see log below)

```ubuntu@propitious-production-rig:~/S3$ npm install
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
loadDep:cdmiclient → addT ▄ ╢██████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
The authenticity of host 'github.com (192.30.255.112)' can't be established.
loadDep:cdmiclient → reso ▄ ╢██████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! git clone --template=/home/ubuntu/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /home/ubuntu/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-8f0c2e6-7531c719: Cloning into bare repository '/home/ubuntu/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-8f0c2e6-7531c719'...
npm ERR! git clone --template=/home/ubuntu/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /home/ubuntu/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-8f0c2e6-7531c719: Warning: Permanently added 'github.com,192.30.255.112' (RSA) to the list of known hosts.
npm ERR! git clone --template=/home/ubuntu/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /home/ubuntu/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-8f0c2e6-7531c719: git@github.com: Permission denied (publickey).
npm ERR! git clone --template=/home/ubuntu/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /home/ubuntu/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-8f0c2e6-7531c719: fatal: Could not read from remote repository.
npm ERR! git clone --template=/home/ubuntu/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /home/ubuntu/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-8f0c2e6-7531c719: 
npm ERR! git clone --template=/home/ubuntu/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /home/ubuntu/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-8f0c2e6-7531c719: Please make sure you have the correct access rights
npm ERR! git clone --template=/home/ubuntu/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /home/ubuntu/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-8f0c2e6-7531c719: and the repository exists.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade

> ioctl@2.0.0 install /home/ubuntu/S3/node_modules/ioctl
> node-gyp rebuild

ubuntu@propitious-production-rig:~/S3$ npm --version
3.5.2

ubuntu@propitious-production-rig:~/S3$ npm start

> @zenko/cloudserver@8.0.0-beta start /home/ubuntu/S3
> npm-run-all --parallel start_dmd start_s3server


> @zenko/cloudserver@8.0.0-beta start_dmd /home/ubuntu/S3
> npm-run-all --parallel start_mdserver start_dataserver


> @zenko/cloudserver@8.0.0-beta start_s3server /home/ubuntu/S3
> node index.js


> @zenko/cloudserver@8.0.0-beta start_mdserver /home/ubuntu/S3
> node mdserver.js


> @zenko/cloudserver@8.0.0-beta start_dataserver /home/ubuntu/S3
> node dataserver.js

module.js:549
    throw err;
    ^

Error: Cannot find module './build/Release/diskusage.node'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/S3/node_modules/diskusage/index.js:1:76)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

npm ERR! Linux 4.15.0-15-generic
npm ERR! argv "/usr/bin/node" "/usr/share/npm/bin/npm-cli.js" "run" "start_s3server"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! @zenko/cloudserver@8.0.0-beta start_s3server: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @zenko/cloudserver@8.0.0-beta start_s3server script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @zenko/cloudserver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @zenko/cloudserver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @zenko/cloudserver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/S3/npm-debug.log
ERROR: "start_s3server" exited with 1.

npm ERR! Linux 4.15.0-15-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! @zenko/cloudserver@8.0.0-beta start: `npm-run-all --parallel start_dmd start_s3server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @zenko/cloudserver@8.0.0-beta start script 'npm-run-all --parallel start_dmd start_s3server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @zenko/cloudserver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all --parallel start_dmd start_s3server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @zenko/cloudserver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @zenko/cloudserver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/S3/npm-debug.log

```

**Comment by YannickFricke** [comment]
@rahulreddy 
Tried on lastest master branch with commit d396acf8fe836a008c307bfd53453aa4ccf1007b

https://asciinema.org/a/ZAJy6JLMkr9JmBKbU1k5ZmMWK

**Comment by YannickFricke** [comment]
Seems to be working with npm 6.1.0

https://asciinema.org/a/AnV7WCyMsFWH5fSEYt8R28tMS

Thank you for your patience :)
