### ISSUE TITLE
Test failing due to cleanup

### ISSUE THREAD

**Issue by LaurenSpiegel** [scality/S3#160]
On a run of integration testing, a test is failing because the deletion of the bucket in the after call is being attempted before the bucket is emptied in the after each.

1) Put object with same key as prior object With v4 signature "after all" hook:
     BucketNotEmpty: The bucket you tried to delete is not empty.
      at Request.extractError (node_modules/aws-sdk/lib/services/s3.js:538:35)
      at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:105:20)

**Comment by LaurenSpiegel** [comment]
Fixed by https://github.com/scality/S3/pull/161
