### ISSUE TITLE
Memory leak warning from file backend if put lots of objects quickly

### ISSUE THREAD

**Issue by LaurenSpiegel** [scality/S3#271]
I am putting 1000 objects at once and this is causing a memory leak warning in the file backend.

From server (I added the console.log):

about to call reConnect in loaddb.  caught err!! [Error: client cannot create new sublevels]
about to call reConnect in loaddb.  caught err!! [Error: client cannot create new sublevels]
about to call reConnect in loaddb.  caught err!! [Error: client cannot create new sublevels]
about to call reConnect in loaddb.  caught err!! [Error: client cannot create new sublevels]
about to call reConnect in loaddb.  caught err!! [Error: client cannot create new sublevels]
about to call reConnect in loaddb.  caught err!! [Error: client cannot create new sublevels](node) warning: possible EventEmitter memory leak detected. 11 recodone listeners added. Use emitter.setMaxListeners() to increase limit.
about to call reConnect in loaddb.  caught err!! [Error: client cannot create new sublevels](node) warning: possible EventEmitter memory leak detected. 11 recodone listeners added. Use emitter.setMaxListeners() to increase limit.

{"name":"S3","clientIP":"::ffff:127.0.0.1","clientPort":61820,"httpMethod":"PUT","httpURL":"/multi-object-delete-234-634/key115","time":1476387139895,"req_id":"812ca3b4b2e18fb7fbd8","level":"info","message":"received request","hostname":"Laurens-MacBook-Pro-3.local","pid":74765}
Trace
    at EventEmitter.addListener (events.js:239:17)
    at EventEmitter.once (events.js:265:8)
    at BucketFileInterface.reConnect (/Users/lhs/Documents/ironman/S3/lib/metadata/bucketfile/backend.js:128:23)
    at /Users/lhs/Documents/ironman/S3/lib/metadata/bucketfile/backend.js:196:22
    at /Users/lhs/Documents/ironman/S3/lib/metadata/bucketfile/backend.js:268:20
    at Stream.<anonymous> (/Users/lhs/Documents/ironman/S3/node_modules/multilevel/node_modules/rpc-stream/index.js:77:10)
    at Stream.stream.write (/Users/lhs/Documents/ironman/S3/node_modules/multilevel/node_modules/rpc-stream/node_modules/through/index.js:26:11)
    at Stream.ondata (stream.js:31:26)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:169:7)
    at Stream.<anonymous> (/Users/lhs/Documents/ironman/S3/node_modules/multilevel/node_modules/mux-demux/inject.js:61:14)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:169:7)
    at Stream.stream.emit (/Users/lhs/Documents/ironman/S3/node_modules/multilevel/node_modules/mux-demux/node_modules/stream-serializer/index.js:60:33)
    at Stream.stream.write (/Users/lhs/Documents/ironman/S3/node_modules/multilevel/node_modules/mux-demux/node_modules/duplex/index.js:68:12)
    at parse (/Users/lhs/Documents/ironman/S3/node_modules/multilevel/node_modules/mux-demux/node_modules/stream-serializer/index.js:29:13)
(node) warning: possible EventEmitter memory leak detected. 11 refdecr listeners added. Use emitter.setMaxListeners() to increase limit.

**Comment by alexandre-merle** [comment]
so the warning come from here https://github.com/scality/S3/blob/master/lib/metadata/bucketfile/backend.js#L128 . We try to reconnect quickly, leading to add a lot of once listener in a few times, that lead to this warning.
The fact is here https://github.com/scality/S3/blob/master/lib/metadata/bucketfile/backend.js#L144 , we should not recall the same function but have another one, and not having '.once' but '.on' listeners.

The more concerning part is the sublevel failure

**Comment by LaurenSpiegel** [comment]
I don't think it's actually doing the process.nextTick/recursive call.  I put a console.log in there and no logs.  It seems the reconnect function itself gets called many times from loadDBIfExistsNoRef.  If you want to play with it, use my ft/batchDelete branch and run the node aws sdk tests.

**Comment by alexandre-merle** [comment]
@LaurenSpiegel will take a look :)

**Comment by alexandre-merle** [comment]
For the listeners, same behavior, we get back an error from sublevel and then trying to reconnect from the  loadDBIfExistsNoRef, explaining this warning. But in local, i can't reproduce your bugs, it is constantly happening ? i see in https://www.npmjs.com/package/level-sublevel , the stability is note as unstable, and we have a release older than the last one, can you try to upgrade this package and see if you still have this issue ?

**Comment by GiorgioRegni** [comment]
So did you try upgrading sublevel?

**Comment by LaurenSpiegel** [comment]
Changing the sublevel version does not help, but my open pr does -- https://github.com/scality/S3/pull/427  😃
