### ISSUE TITLE
TypeError: this is not a typed array

### ISSUE THREAD

**Issue by rusher81572** [scality/S3#303]
Hello,

Today 10/21/2016 I tried to start the S3 server using Node.js v4.0.0:

git clone....
npm install
npm start

I get this error:

> s3@1.1.0 start /Users/rusher81572/S3
> node init.js && node index.js

{"name":"S3","level":"warn","message":"WARNING: Synchronization directory updates are not supported on this platform. Newly written data could be lost if your system crashes before the operating system is able to write directory updates.","hostname":"MacBook-Pro.local","pid":42471}
{"name":"S3","level":"info","message":"Init complete.  Go forth and store data.","hostname":"MacBook-Pro.local","pid":42471}
/Users/rusher81572/S3/node_modules/sproxydclient/lib/keygen.js:5
const sid = Buffer.from([0x59]);
                   ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/Users/rusher81572/S3/node_modules/sproxydclient/lib/keygen.js:5:20)
    at Module._compile (module.js:434:26)
    at Module._extensions..js (module.js:452:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/rusher81572/S3/node_modules/babel-core/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/rusher81572/S3/node_modules/sproxydclient/lib/sproxyd.js:9:16)
    at Module._compile (module.js:434:26)
    at Module._extensions..js (module.js:452:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/rusher81572/S3/node_modules/babel-core/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! s3@1.1.0 start: `node init.js && node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the s3@1.1.0 start script 'node init.js && node index.js'.
npm ERR! This is most likely a problem with the s3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node init.js && node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls s3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by rusher81572** [comment]
My bad, needed newer node.js version
