### ISSUE TITLE
Trouble running S3 server on Linux with Docker

### ISSUE THREAD

**Issue by rusher81572** [scality/S3#337]
Hello, I am trying to get this to run in Docker on generic Ubuntu but it never runs
properly unless you use the official Node.js image like in your Dockerfile. On my Mac,
the S3 server runs perfectly fine just not on Linux with Docker.

Node.js v4.6.1

Here is My Dockerfile:

```
FROM ubuntu:16.10
USER root
VOLUME /data
VOLUME /metadata
ENV S3DATAPATH "/data"
ENV S3METADATAPATH "/metadata"
RUN apt-get update;apt-get install -y nodejs npm git
RUN git clone https://github.com/scality/S3.git
WORKDIR /S3
RUN ln -s /usr/bin/nodejs /usr/bin/node
RUN npm install
CMD [ "npm", "start" ]
```

The error when the program runs

```
/S3/node_modules/sproxydclient/lib/keygen.js:5
const sid = Buffer.from([0x59]);
                   ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/S3/node_modules/sproxydclient/lib/keygen.js:5:20)
    at Module._compile (module.js:410:26)
    at Module._extensions..js (module.js:417:10)
    at Object.require.extensions.(anonymous function) [as .js] (/S3/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/S3/node_modules/sproxydclient/lib/sproxyd.js:9:16)
    at Module._compile (module.js:410:26)
    at Module._extensions..js (module.js:417:10)
    at Object.require.extensions.(anonymous function) [as .js] (/S3/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

npm ERR! Linux 4.4.20-moby
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! s3@1.1.0 start: `node init.js && node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the s3@1.1.0 start script 'node init.js && node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the s3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node init.js && node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs s3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls s3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /S3/npm-debug.log
```

**Comment by GiorgioRegni** [comment]
It seems that with your dockerfile/ubuntu 16.10, you don't have the right version of node. Can you check what version comes with ubuntu:16.10?
We're using node 4 in our Dockerfile,

**Comment by rusher81572** [comment]
Ubuntu 16.10 ships with Node.js v4.6.1. Isn't that the same as node4? The Mac version that works is v4.6.1 also.

**Comment by alexandre-merle** [comment]
Hello, according to your npm output, the node version seems to be 'node v4.2.6' inside your docker, when S3 require at least 'node v4.5.0' :)

**Comment by rusher81572** [comment]
Ah ok. The README says 4.2 or higher. Thanks, will try it later.

**Comment by rusher81572** [comment]
Thanks for the help. Resolved issue with the following Dockerfile. Might be useful for sharing. 
```
FROM ubuntu
USER root
ENV S3DATAPATH "/data"
ENV S3METADATAPATH "/metadata"
RUN apt-get update;apt-get install -y git curl build-essential python
RUN curl -sL https://deb.nodesource.com/setup_4.x -o nodesource_setup.sh
RUN bash nodesource_setup.sh
RUN apt-get install -y nodejs
RUN git clone https://github.com/scality/S3.git /usr/src/app
WORKDIR /usr/src/app
RUN npm install
CMD [ "npm", "start" ]
```
