### ISSUE TITLE
put-bucket-acl crash worker

### ISSUE THREAD

**Issue by alexandre-merle** [scality/S3#398]
this command ```aws --endpoint-url=http://127.0.0.1:8000 s3api put-bucket-acl --bucket bucket2 --grant-read public``` result in a crash of the s3 worker :

```
{"name":"S3","error":"Cannot read property 'trim' of undefined","stack":"TypeError: Cannot read property 'trim' of undefined\n    at /home/scality/S3/lib/utilities/aclUtils.js:162:22\n    at Array.map (native)\n    at Object.parseGrant (/home/scality/S3/lib/utilities/aclUtils.js:159:23)\n    at Object.bucketPutACL (/home/scality/S3/lib/api/bucketPutACL.js:83:18)\n    at /home/scality/S3/lib/api/api.js:84:20\n    at vaultSignatureCb (/home/scality/S3/lib/auth/vault.js:55:12)\n    at /home/scality/S3/lib/auth/vault.js:97:28\n    at /home/scality/S3/node_modules/vaultclient/lib/IAMClient.js:221:20\n    at /home/scality/S3/node_modules/vaultclient/lib/IAMClient.js:540:24\n    at IAMClient.getObj (/home/scality/S3/node_modules/vaultclient/lib/IAMClient.js:523:57)\n    at IAMClient.handleResponse (/home/scality/S3/node_modules/vaultclient/lib/IAMClient.js:534:14)\n    at IncomingMessage.<anonymous> (/home/scality/S3/node_modules/vaultclient/lib/IAMClient.js:467:22)\n    at emitNone (events.js:72:20)\n    at IncomingMessage.emit (events.js:166:7)\n    at endReadableNT (_stream_readable.js:921:12)\n    at nextTickCallbackWith2Args (node.js:442:9)","level":"fatal","message":"caught error","hostname":"localhost","pid":90}
```

**Comment by LaurenSpiegel** [comment]
Because you're not supposed to do that :)

If you're setting a canned acl you are supposed to do it with the x-amz-acl header.  AWS responds to your request with InvalidArgument.  I will fix so that we are just as graceful.

**Comment by alexandre-merle** [comment]
yes i find this after doing the command :)

**Comment by LaurenSpiegel** [comment]
fixed by https://github.com/scality/S3/commit/3771c965cb5fb9256d59c5f0eb9235322f9062bf
