### ISSUE TITLE
Missing object key in multipart upload request crashes S3

### ISSUE THREAD

**Issue by vrancurel** [scality/S3#538]
Version: 6.2.15

```
"error":"Invalid string length","stack":"RangeError: Invalid string length\n    at IncomingMessage.<anonymous> (/home/scality/S3/lib/routes/routePUT.js:27:35)\n    at emitOne (events.js:77:13)\n    at IncomingMessage.emit (events.js:169:7)\n    at readableAddChunk (_stream_readable.js:153:18)\n    at IncomingMessage.Readable.push (_stream_readable.js:111:10)\n    at HTTPParser.parserOnBody (_http_common.js:127:22)","level":"fatal","message":"caught error","hostname":"srv.domain.io","pid":18444}
{"name":"S3","time":1484929024652,"level":"error","message":"shutdown of worker due to exception","hostname":"srv.domain.io","pid":18444}
{"name":"S3","time":1484929024660,"workerId":2850,"level":"error","message":"worker disconnected. making sure exits","hostname":"srv.domain.io","pid":118}
```

**Comment by LaurenSpiegel** [comment]
Fixed by #534 and #540
