### ISSUE TITLE
utapi crashing on range request

### ISSUE THREAD

**Issue by msegura** [scality/S3#557]
Probably not a major threat for the service, however the following pop'ed up in the log:

```
{"name":"Utapi","time":1485200276474,"error":"Invalid status code: 0","stack":["RangeError: Invalid status code: 0","at ServerResponse.writeHead (_http_server.js:192:11)","at UtapiServer.response (/home/scality/S3/node_modules/utapi/dist/lib/server.js:183:13)","at UtapiServer.errorResponse (/home/scality/S3/node_modules/utapi/dist/lib/server.js:202:21)","at /home/scality/S3/node_modules/utapi/dist/lib/server.js:100:29","at /home/scality/S3/node_modules/utapi/dist/router/Router.js:280:24","at /home/scality/S3/node_modules/utapi/dist/router/Router.js:239:24","at /home/scality/S3/node_modules/utapi/dist/lib/Vault.js:75:24","at /home/scality/S3/node_modules/vaultclient/lib/IAMClient.js:275:24","at ClientRequest.<anonymous> (/home/scality/S3/node_modules/vaultclient/lib/IAMClient.js:428:20)","at emitOne (events.js:77:13)","at ClientRequest.emit (events.js:169:7)","at Socket.socketErrorListener (_http_client.js:269:9)","at emitOne (events.js:77:13)","at Socket.emit (events.js:169:7)","at emitErrorNT (net.js:1269:8)","at nextTickCallbackWith2Args (node.js:442:9)"],"level":"fatal","message":"caught error","hostname":"there.nowhere.com","pid":31197} 

```

**Comment by LaurenSpiegel** [comment]
please open in utapi
