### ISSUE TITLE
HTTPS: Fatal error evaluating certificates - S3 client gets ECONNRESET

### ISSUE THREAD

**Issue by dkilcy** [scality/S3#86]
GA1.0.3
CentOS 7

I created a certificate, key and CA certificate according to the guidelines in Federation/Using.md 
My s3cmd client returns ECONNRESET.    The S3  See snippet from s3 log below.
The S3/lib/auth code is failing to correctly parse an error reported from the signature callback and is throwing an exception causing an ECONNRESET to the client.

There are 2 problems:

1. It appears the signature code is trying to evaluate "host.local." instead of "host.local", causing the authentication to fail.
2. When this response is returned to the client, the XML response is not well-formed, and the vault module throws a TypeError

TLS creation:
```
openssl genrsa -out ca.key 2048
openssl req -new -x509 -extensions v3_ca -key ca.key -out ca.crt -days 99999 -subj "/C=US/ST=Country/L=City/O=Organization/CN=local
openssl genrsa -out test.key 2048
openssl req -new -key test.key -out test.csr -subj "/C=US/ST=Country/L=City/O=Organization/CN=*.local" 
openssl x509 -req -in test.csr -CA ca.crt -CAkey ca.key -CAcreateserial  -out test.crt -days 99999 -sha256
```

My s3cmd output:
```
DEBUG: Sending request method_string='GET', uri='/', headers={'Authorization': 'AWS 6XCJ7R7FUT9UYQJ6DC0Y:MSaSzYkmx5ASSQk/HNcuCcQGRss=', 'x-amz-date': 'Sat, 02 Jul 2016 15:44:51 +0000'}, body=(0 bytes)
DEBUG: ConnMan.put(): closing over-used connection
WARNING: Retrying failed request: / (HTTP/1.1 ECONNRESET unknown
)
WARNING: Waiting 3 sec...
```

Complete log snippet from /logs/s3-0.log
```
{"name":"S3","clientIP":"::ffff:10.241.127.20","clientPort":45347,"httpMethod":"GET","httpURL":"/","time":1467474291518,"req_id":"e7284dcf488afcb4e14c","level":"info","message":"received request","hostname":"libbbqconn01.local","pid":72}
{"name":"S3","clientIP":"::ffff:10.241.127.20","clientPort":45347,"httpMethod":"GET","httpURL":"/","time":1467474291518,"req_id":"e7284dcf488afcb4e14c","level":"info","message":"received request","hostname":"libbbqconn01.local","pid":72}
{"name":"S3","method":"routerGET","time":1467474291521,"req_id":"e7284dcf488afcb4e14c","level":"debug","message":"routing request","hostname":"libbbqconn01.local","pid":72}
{"name":"S3","method":"auth","time":1467474291521,"req_id":"e7284dcf488afcb4e14c","level":"debug","message":"running auth checks","hostname":"libbbqconn01.local","pid":72}
{"name":"S3","authHeader":"AWS 6XCJ7R7FUT9UYQJ6DC0Y:MSaSzYkmx5ASSQk/HNcuCcQGRss=","time":1467474291521,"req_id":"e7284dcf488afcb4e14c","level":"trace","message":"authorization header","hostname":"libbbqconn01.local","pid":72}
{"name":"S3","time":1467474291521,"req_id":"e7284dcf488afcb4e14c","level":"trace","message":"authenticating request with auth v2 using headers","hostname":"libbbqconn01.local","pid":72}
{"name":"S3","time":1467474291522,"req_id":"e7284dcf488afcb4e14c","level":"trace","message":"running header auth check","hostname":"libbbqconn01.local","pid":72}
{"name":"S3","requestTimestamp":1467474291000,"time":1467474291522,"req_id":"e7284dcf488afcb4e14c","level":"trace","message":"request timestamp","hostname":"libbbqconn01.local","pid":72}
{"name":"S3","currentTimestamp":1467474291522,"time":1467474291522,"req_id":"e7284dcf488afcb4e14c","level":"trace","message":"current timestamp","hostname":"libbbqconn01.local","pid":72}
{"name":"S3","accessKey":"6XCJ7R7FUT9UYQJ6DC0Y","signatureFromRequest":"MSaSzYkmx5ASSQk/HNcuCcQGRss=","time":1467474291522,"req_id":"e7284dcf488afcb4e14c","level":"trace","message":"signature from request","hostname":"libbbqconn01.local","pid":72}
{"name":"S3","accessKey":"6XCJ7R7FUT9UYQJ6DC0Y","time":1467474291523,"req_id":"e7284dcf488afcb4e14c","level":"trace","message":"constructing string to sign","hostname":"libbbqconn01.local","pid":72}
{"name":"S3","accessKey":"6XCJ7R7FUT9UYQJ6DC0Y","stringToSign":"GET\n\n\n\nx-amz-date:Sat, 02 Jul 2016 15:44:51 +0000\n/","time":1467474291524,"req_id":"e7284dcf488afcb4e14c","level":"trace","message":"constructed string to sign","hostname":"libbbqconn01.local","pid":72}
{"name":"S3","accessKey":"6XCJ7R7FUT9UYQJ6DC0Y","algo":"sha1","time":1467474291524,"req_id":"e7284dcf488afcb4e14c","level":"trace","message":"algo for calculating signature","hostname":"libbbqconn01.local","pid":72}
{"name":"S3","accessKey":"6XCJ7R7FUT9UYQJ6DC0Y","time":1467474291524,"req_id":"e7284dcf488afcb4e14c","level":"debug","message":"authenticating V2 request","hostname":"libbbqconn01.local","pid":72}
{"name":"S3","accessKey":"6XCJ7R7FUT9UYQJ6DC0Y","errorMessage":{"reason":"Host: lb1bbqconn01.local. is not cert's CN: *.local","host":"lb1bbqconn01.local.","cert":{"subject":{"C":"US","ST":"Country","L":"City","O":"Organization","CN":"*.local"},"issuer":{"C":"US","ST":"Country","L":"City","O":"Organization","CN":"local"},"modulus":"BC82E630F6C93D3A56C1530CC23C3CE56CD7027BD56F7DBC2EC1408BBAA3FB13F49B3A1AF9C839781D3C0CA7308A3B822DE504BD58B3111798F65136B29664F42F1E5277822C8336B622B13272121AD8B8B3AA0D4DFD70F80BF57792ECA400474D2260BB2810D4292422CB223F2D0226DC931E35E56BB2751A3E26594E11B544FE8DD2B09F5E25485C9DA67D01EC1611480D6569485E0EEAA3703ED0E944CF724EB683146EDBEA2858E088E0148FE6D9505BAD1EDBDAD65DF53F4077C8F84D2ED8F9453FFC990959FD7048E390FB96D8E3F416E3934A06FD3337C244EC40AC16AEE360700ECBB4A42407D3B10288FE29C960A63E49AC09D5D5F0B10DDE223B67","exponent":"0x10001","valid_from":"Jul  1 19:38:55 2016 GMT","valid_to":"Apr 15 19:38:55 2290 GMT","fingerprint":"45:59:C9:28:B6:CF:54:9F:D8:F4:2A:FA:57:B0:34:9F:32:9A:9C:9F","serialNumber":"ABBEF04ED4673BF0","raw":{"type":"Buffer","data":[48,130,3,42,48,130,2,18,2,9,0,171,190,240,78,212,103,59,240,48,13,6,9,42,134,72,134,247,13,1,1,11,5,0,48,85,49,11,48,9,6,3,85,4,6,19,2,85,83,49,16,48,14,6,3,85,4,8,12,7,67,111,117,110,116,114,121,49,13,48,11,6,3,85,4,7,12,4,67,105,116,121,49,21,48,19,6,3,85,4,10,12,12,79,114,103,97,110,105,122,97,116,105,111,110,49,14,48,12,6,3,85,4,3,12,5,108,111,99,97,108,48,32,23,13,49,54,48,55,48,49,49,57,51,56,53,53,90,24,15,50,50,57,48,48,52,49,53,49,57,51,56,53,53,90,48,87,49,11,48,9,6,3,85,4,6,19,2,85,83,49,16,48,14,6,3,85,4,8,12,7,67,111,117,110,116,114,121,49,13,48,11,6,3,85,4,7,12,4,67,105,116,121,49,21,48,19,6,3,85,4,10,12,12,79,114,103,97,110,105,122,97,116,105,111,110,49,16,48,14,6,3,85,4,3,12,7,42,46,108,111,99,97,108,48,130,1,34,48,13,6,9,42,134,72,134,247,13,1,1,1,5,0,3,130,1,15,0,48,130,1,10,2,130,1,1,0,188,130,230,48,246,201,61,58,86,193,83,12,194,60,60,229,108,215,2,123,213,111,125,188,46,193,64,139,186,163,251,19,244,155,58,26,249,200,57,120,29,60,12,167,48,138,59,130,45,229,4,189,88,179,17,23,152,246,81,54,178,150,100,244,47,30,82,119,130,44,131,54,182,34,177,50,114,18,26,216,184,179,170,13,77,253,112,248,11,245,119,146,236,164,0,71,77,34,96,187,40,16,212,41,36,34,203,34,63,45,2,38,220,147,30,53,229,107,178,117,26,62,38,89,78,17,181,68,254,141,210,176,159,94,37,72,92,157,166,125,1,236,22,17,72,13,101,105,72,94,14,234,163,112,62,208,233,68,207,114,78,182,131,20,110,219,234,40,88,224,136,224,20,143,230,217,80,91,173,30,219,218,214,93,245,63,64,119,200,248,77,46,216,249,69,63,252,153,9,89,253,112,72,227,144,251,150,216,227,244,22,227,147,74,6,253,51,55,194,68,236,64,172,22,174,227,96,112,14,203,180,164,36,7,211,177,2,136,254,41,201,96,166,62,73,172,9,213,213,240,177,13,222,34,59,103,2,3,1,0,1,48,13,6,9,42,134,72,134,247,13,1,1,11,5,0,3,130,1,1,0,189,254,51,106,51,125,164,100,154,183,21,67,30,2,241,130,81,102,221,31,40,114,102,210,112,123,18,248,112,19,51,5,98,223,242,238,184,40,88,165,192,247,26,117,65,159,64,140,59,160,213,13,244,194,140,24,23,63,28,130,12,93,165,189,238,136,158,220,9,221,159,209,226,120,255,206,159,39,196,171,4,171,50,44,239,28,160,67,244,205,85,233,142,154,253,113,125,50,16,251,134,20,134,184,107,167,165,174,217,13,238,156,16,47,99,26,167,15,99,66,223,202,172,135,129,133,215,176,53,81,99,172,12,0,89,58,174,204,5,119,238,131,45,93,230,155,140,67,28,90,19,135,110,95,238,211,140,248,156,164,0,202,186,215,135,60,12,63,63,99,104,143,165,98,135,254,62,124,178,207,69,44,8,207,229,84,164,46,250,213,146,3,251,248,240,52,57,162,240,188,232,109,11,131,79,70,235,77,141,234,204,131,31,94,52,138,198,205,182,90,189,117,91,98,82,41,17,136,53,255,189,95,241,236,88,221,141,145,204,0,27,132,126,232,164,133,14,197,9,138,114,28,138,43,204,12]}}},"time":1467474291563,"req_id":"e7284dcf488afcb4e14c","level":"error","message":"received error message from vault","hostname":"libbbqconn01.local","pid":72}
{"name":"S3","accessKey":"6XCJ7R7FUT9UYQJ6DC0Y","error":{"reason":"Host: lb1bbqconn01.local. is not cert's CN: *.local","host":"lb1bbqconn01.local.","cert":{"subject":{"C":"US","ST":"Country","L":"City","O":"Organization","CN":"*.local"},"issuer":{"C":"US","ST":"Country","L":"City","O":"Organization","CN":"local"},"modulus":"BC82E630F6C93D3A56C1530CC23C3CE56CD7027BD56F7DBC2EC1408BBAA3FB13F49B3A1AF9C839781D3C0CA7308A3B822DE504BD58B3111798F65136B29664F42F1E5277822C8336B622B13272121AD8B8B3AA0D4DFD70F80BF57792ECA400474D2260BB2810D4292422CB223F2D0226DC931E35E56BB2751A3E26594E11B544FE8DD2B09F5E25485C9DA67D01EC1611480D6569485E0EEAA3703ED0E944CF724EB683146EDBEA2858E088E0148FE6D9505BAD1EDBDAD65DF53F4077C8F84D2ED8F9453FFC990959FD7048E390FB96D8E3F416E3934A06FD3337C244EC40AC16AEE360700ECBB4A42407D3B10288FE29C960A63E49AC09D5D5F0B10DDE223B67","exponent":"0x10001","valid_from":"Jul  1 19:38:55 2016 GMT","valid_to":"Apr 15 19:38:55 2290 GMT","fingerprint":"45:59:C9:28:B6:CF:54:9F:D8:F4:2A:FA:57:B0:34:9F:32:9A:9C:9F","serialNumber":"ABBEF04ED4673BF0","raw":{"type":"Buffer","data":[48,130,3,42,48,130,2,18,2,9,0,171,190,240,78,212,103,59,240,48,13,6,9,42,134,72,134,247,13,1,1,11,5,0,48,85,49,11,48,9,6,3,85,4,6,19,2,85,83,49,16,48,14,6,3,85,4,8,12,7,67,111,117,110,116,114,121,49,13,48,11,6,3,85,4,7,12,4,67,105,116,121,49,21,48,19,6,3,85,4,10,12,12,79,114,103,97,110,105,122,97,116,105,111,110,49,14,48,12,6,3,85,4,3,12,5,108,111,99,97,108,48,32,23,13,49,54,48,55,48,49,49,57,51,56,53,53,90,24,15,50,50,57,48,48,52,49,53,49,57,51,56,53,53,90,48,87,49,11,48,9,6,3,85,4,6,19,2,85,83,49,16,48,14,6,3,85,4,8,12,7,67,111,117,110,116,114,121,49,13,48,11,6,3,85,4,7,12,4,67,105,116,121,49,21,48,19,6,3,85,4,10,12,12,79,114,103,97,110,105,122,97,116,105,111,110,49,16,48,14,6,3,85,4,3,12,7,42,46,108,111,99,97,108,48,130,1,34,48,13,6,9,42,134,72,134,247,13,1,1,1,5,0,3,130,1,15,0,48,130,1,10,2,130,1,1,0,188,130,230,48,246,201,61,58,86,193,83,12,194,60,60,229,108,215,2,123,213,111,125,188,46,193,64,139,186,163,251,19,244,155,58,26,249,200,57,120,29,60,12,167,48,138,59,130,45,229,4,189,88,179,17,23,152,246,81,54,178,150,100,244,47,30,82,119,130,44,131,54,182,34,177,50,114,18,26,216,184,179,170,13,77,253,112,248,11,245,119,146,236,164,0,71,77,34,96,187,40,16,212,41,36,34,203,34,63,45,2,38,220,147,30,53,229,107,178,117,26,62,38,89,78,17,181,68,254,141,210,176,159,94,37,72,92,157,166,125,1,236,22,17,72,13,101,105,72,94,14,234,163,112,62,208,233,68,207,114,78,182,131,20,110,219,234,40,88,224,136,224,20,143,230,217,80,91,173,30,219,218,214,93,245,63,64,119,200,248,77,46,216,249,69,63,252,153,9,89,253,112,72,227,144,251,150,216,227,244,22,227,147,74,6,253,51,55,194,68,236,64,172,22,174,227,96,112,14,203,180,164,36,7,211,177,2,136,254,41,201,96,166,62,73,172,9,213,213,240,177,13,222,34,59,103,2,3,1,0,1,48,13,6,9,42,134,72,134,247,13,1,1,11,5,0,3,130,1,1,0,189,254,51,106,51,125,164,100,154,183,21,67,30,2,241,130,81,102,221,31,40,114,102,210,112,123,18,248,112,19,51,5,98,223,242,238,184,40,88,165,192,247,26,117,65,159,64,140,59,160,213,13,244,194,140,24,23,63,28,130,12,93,165,189,238,136,158,220,9,221,159,209,226,120,255,206,159,39,196,171,4,171,50,44,239,28,160,67,244,205,85,233,142,154,253,113,125,50,16,251,134,20,134,184,107,167,165,174,217,13,238,156,16,47,99,26,167,15,99,66,223,202,172,135,129,133,215,176,53,81,99,172,12,0,89,58,174,204,5,119,238,131,45,93,230,155,140,67,28,90,19,135,110,95,238,211,140,248,156,164,0,202,186,215,135,60,12,63,63,99,104,143,165,98,135,254,62,124,178,207,69,44,8,207,229,84,164,46,250,213,146,3,251,248,240,52,57,162,240,188,232,109,11,131,79,70,235,77,141,234,204,131,31,94,52,138,198,205,182,90,189,117,91,98,82,41,17,136,53,255,189,95,241,236,88,221,141,145,204,0,27,132,126,232,164,133,14,197,9,138,114,28,138,43,204,12]}}},"time":1467474291565,"req_id":"e7284dcf488afcb4e14c","level":"warn","message":"authentication error","hostname":"libbbqconn01.local","pid":72}
{"name":"S3","error":"Cannot read property 'toString' of undefined","stack":"TypeError: Cannot read property 'toString' of undefined\n    at ServerResponse.writeHead (_http_server.js:190:44)\n    at errorXMLResponse (routesUtils.js:87:14)\n    at Object.responseXMLBody (routesUtils.js:149:20)\n    at routeGET.js:10:25\n    at api.js:28:24\n    at headerAuthCheck.js:58:24\n    at vaultSignatureCb (vault.js:47:16)\n    at ClientRequest.<anonymous> (vault.js:72:24)\n    at emitOne (events.js:77:13)\n    at ClientRequest.emit (events.js:169:7)","level":"fatal","message":"caught error","hostname":"libbbqconn01.local","pid":72}
{"name":"S3","level":"error","message":"shutdown of worker due to exception","hostname":"libbbqconn01.local","pid":72}
{"name":"S3","accessKey":"6XCJ7R7FUT9UYQJ6DC0Y","error":{"reason":"Host: lb1bbqconn01.local. is not cert's CN: *.local","host":"lb1bbqconn01.local.","cert":{"subject":{"C":"US","ST":"Country","L":"City","O":"Organization","CN":"*.local"},"issuer":{"C":"US","ST":"Country","L":"City","O":"Organization","CN":"local"},"modulus":"BC82E630F6C93D3A56C1530CC23C3CE56CD7027BD56F7DBC2EC1408BBAA3FB13F49B3A1AF9C839781D3C0CA7308A3B822DE504BD58B3111798F65136B29664F42F1E5277822C8336B622B13272121AD8B8B3AA0D4DFD70F80BF57792ECA400474D2260BB2810D4292422CB223F2D0226DC931E35E56BB2751A3E26594E11B544FE8DD2B09F5E25485C9DA67D01EC1611480D6569485E0EEAA3703ED0E944CF724EB683146EDBEA2858E088E0148FE6D9505BAD1EDBDAD65DF53F4077C8F84D2ED8F9453FFC990959FD7048E390FB96D8E3F416E3934A06FD3337C244EC40AC16AEE360700ECBB4A42407D3B10288FE29C960A63E49AC09D5D5F0B10DDE223B67","exponent":"0x10001","valid_from":"Jul  1 19:38:55 2016 GMT","valid_to":"Apr 15 19:38:55 2290 GMT","fingerprint":"45:59:C9:28:B6:CF:54:9F:D8:F4:2A:FA:57:B0:34:9F:32:9A:9C:9F","serialNumber":"ABBEF04ED4673BF0","raw":{"type":"Buffer","data":[48,130,3,42,48,130,2,18,2,9,0,171,190,240,78,212,103,59,240,48,13,6,9,42,134,72,134,247,13,1,1,11,5,0,48,85,49,11,48,9,6,3,85,4,6,19,2,85,83,49,16,48,14,6,3,85,4,8,12,7,67,111,117,110,116,114,121,49,13,48,11,6,3,85,4,7,12,4,67,105,116,121,49,21,48,19,6,3,85,4,10,12,12,79,114,103,97,110,105,122,97,116,105,111,110,49,14,48,12,6,3,85,4,3,12,5,108,111,99,97,108,48,32,23,13,49,54,48,55,48,49,49,57,51,56,53,53,90,24,15,50,50,57,48,48,52,49,53,49,57,51,56,53,53,90,48,87,49,11,48,9,6,3,85,4,6,19,2,85,83,49,16,48,14,6,3,85,4,8,12,7,67,111,117,110,116,114,121,49,13,48,11,6,3,85,4,7,12,4,67,105,116,121,49,21,48,19,6,3,85,4,10,12,12,79,114,103,97,110,105,122,97,116,105,111,110,49,16,48,14,6,3,85,4,3,12,7,42,46,108,111,99,97,108,48,130,1,34,48,13,6,9,42,134,72,134,247,13,1,1,1,5,0,3,130,1,15,0,48,130,1,10,2,130,1,1,0,188,130,230,48,246,201,61,58,86,193,83,12,194,60,60,229,108,215,2,123,213,111,125,188,46,193,64,139,186,163,251,19,244,155,58,26,249,200,57,120,29,60,12,167,48,138,59,130,45,229,4,189,88,179,17,23,152,246,81,54,178,150,100,244,47,30,82,119,130,44,131,54,182,34,177,50,114,18,26,216,184,179,170,13,77,253,112,248,11,245,119,146,236,164,0,71,77,34,96,187,40,16,212,41,36,34,203,34,63,45,2,38,220,147,30,53,229,107,178,117,26,62,38,89,78,17,181,68,254,141,210,176,159,94,37,72,92,157,166,125,1,236,22,17,72,13,101,105,72,94,14,234,163,112,62,208,233,68,207,114,78,182,131,20,110,219,234,40,88,224,136,224,20,143,230,217,80,91,173,30,219,218,214,93,245,63,64,119,200,248,77,46,216,249,69,63,252,153,9,89,253,112,72,227,144,251,150,216,227,244,22,227,147,74,6,253,51,55,194,68,236,64,172,22,174,227,96,112,14,203,180,164,36,7,211,177,2,136,254,41,201,96,166,62,73,172,9,213,213,240,177,13,222,34,59,103,2,3,1,0,1,48,13,6,9,42,134,72,134,247,13,1,1,11,5,0,3,130,1,1,0,189,254,51,106,51,125,164,100,154,183,21,67,30,2,241,130,81,102,221,31,40,114,102,210,112,123,18,248,112,19,51,5,98,223,242,238,184,40,88,165,192,247,26,117,65,159,64,140,59,160,213,13,244,194,140,24,23,63,28,130,12,93,165,189,238,136,158,220,9,221,159,209,226,120,255,206,159,39,196,171,4,171,50,44,239,28,160,67,244,205,85,233,142,154,253,113,125,50,16,251,134,20,134,184,107,167,165,174,217,13,238,156,16,47,99,26,167,15,99,66,223,202,172,135,129,133,215,176,53,81,99,172,12,0,89,58,174,204,5,119,238,131,45,93,230,155,140,67,28,90,19,135,110,95,238,211,140,248,156,164,0,202,186,215,135,60,12,63,63,99,104,143,165,98,135,254,62,124,178,207,69,44,8,207,229,84,164,46,250,213,146,3,251,248,240,52,57,162,240,188,232,109,11,131,79,70,235,77,141,234,204,131,31,94,52,138,198,205,182,90,189,117,91,98,82,41,17,136,53,255,189,95,241,236,88,221,141,145,204,0,27,132,126,232,164,133,14,197,9,138,114,28,138,43,204,12]}}},"time":1467474291565,"req_id":"e7284dcf488afcb4e14c","level":"warn","message":"authentication error","hostname":"libbbqconn01.local","pid":72}
{"name":"S3","accessKey":"6XCJ7R7FUT9UYQJ6DC0Y","errCode":{"reason":"Host: lb1bbqconn01.local. is not cert's CN: *.local","host":"lb1bbqconn01.local.","cert":{"subject":{"C":"US","ST":"Country","L":"City","O":"Organization","CN":"*.local"},"issuer":{"C":"US","ST":"Country","L":"City","O":"Organization","CN":"local"},"modulus":"BC82E630F6C93D3A56C1530CC23C3CE56CD7027BD56F7DBC2EC1408BBAA3FB13F49B3A1AF9C839781D3C0CA7308A3B822DE504BD58B3111798F65136B29664F42F1E5277822C8336B622B13272121AD8B8B3AA0D4DFD70F80BF57792ECA400474D2260BB2810D4292422CB223F2D0226DC931E35E56BB2751A3E26594E11B544FE8DD2B09F5E25485C9DA67D01EC1611480D6569485E0EEAA3703ED0E944CF724EB683146EDBEA2858E088E0148FE6D9505BAD1EDBDAD65DF53F4077C8F84D2ED8F9453FFC990959FD7048E390FB96D8E3F416E3934A06FD3337C244EC40AC16AEE360700ECBB4A42407D3B10288FE29C960A63E49AC09D5D5F0B10DDE223B67","exponent":"0x10001","valid_from":"Jul  1 19:38:55 2016 GMT","valid_to":"Apr 15 19:38:55 2290 GMT","fingerprint":"45:59:C9:28:B6:CF:54:9F:D8:F4:2A:FA:57:B0:34:9F:32:9A:9C:9F","serialNumber":"ABBEF04ED4673BF0","raw":{"type":"Buffer","data":[48,130,3,42,48,130,2,18,2,9,0,171,190,240,78,212,103,59,240,48,13,6,9,42,134,72,134,247,13,1,1,11,5,0,48,85,49,11,48,9,6,3,85,4,6,19,2,85,83,49,16,48,14,6,3,85,4,8,12,7,67,111,117,110,116,114,121,49,13,48,11,6,3,85,4,7,12,4,67,105,116,121,49,21,48,19,6,3,85,4,10,12,12,79,114,103,97,110,105,122,97,116,105,111,110,49,14,48,12,6,3,85,4,3,12,5,108,111,99,97,108,48,32,23,13,49,54,48,55,48,49,49,57,51,56,53,53,90,24,15,50,50,57,48,48,52,49,53,49,57,51,56,53,53,90,48,87,49,11,48,9,6,3,85,4,6,19,2,85,83,49,16,48,14,6,3,85,4,8,12,7,67,111,117,110,116,114,121,49,13,48,11,6,3,85,4,7,12,4,67,105,116,121,49,21,48,19,6,3,85,4,10,12,12,79,114,103,97,110,105,122,97,116,105,111,110,49,16,48,14,6,3,85,4,3,12,7,42,46,108,111,99,97,108,48,130,1,34,48,13,6,9,42,134,72,134,247,13,1,1,1,5,0,3,130,1,15,0,48,130,1,10,2,130,1,1,0,188,130,230,48,246,201,61,58,86,193,83,12,194,60,60,229,108,215,2,123,213,111,125,188,46,193,64,139,186,163,251,19,244,155,58,26,249,200,57,120,29,60,12,167,48,138,59,130,45,229,4,189,88,179,17,23,152,246,81,54,178,150,100,244,47,30,82,119,130,44,131,54,182,34,177,50,114,18,26,216,184,179,170,13,77,253,112,248,11,245,119,146,236,164,0,71,77,34,96,187,40,16,212,41,36,34,203,34,63,45,2,38,220,147,30,53,229,107,178,117,26,62,38,89,78,17,181,68,254,141,210,176,159,94,37,72,92,157,166,125,1,236,22,17,72,13,101,105,72,94,14,234,163,112,62,208,233,68,207,114,78,182,131,20,110,219,234,40,88,224,136,224,20,143,230,217,80,91,173,30,219,218,214,93,245,63,64,119,200,248,77,46,216,249,69,63,252,153,9,89,253,112,72,227,144,251,150,216,227,244,22,227,147,74,6,253,51,55,194,68,236,64,172,22,174,227,96,112,14,203,180,164,36,7,211,177,2,136,254,41,201,96,166,62,73,172,9,213,213,240,177,13,222,34,59,103,2,3,1,0,1,48,13,6,9,42,134,72,134,247,13,1,1,11,5,0,3,130,1,1,0,189,254,51,106,51,125,164,100,154,183,21,67,30,2,241,130,81,102,221,31,40,114,102,210,112,123,18,248,112,19,51,5,98,223,242,238,184,40,88,165,192,247,26,117,65,159,64,140,59,160,213,13,244,194,140,24,23,63,28,130,12,93,165,189,238,136,158,220,9,221,159,209,226,120,255,206,159,39,196,171,4,171,50,44,239,28,160,67,244,205,85,233,142,154,253,113,125,50,16,251,134,20,134,184,107,167,165,174,217,13,238,156,16,47,99,26,167,15,99,66,223,202,172,135,129,133,215,176,53,81,99,172,12,0,89,58,174,204,5,119,238,131,45,93,230,155,140,67,28,90,19,135,110,95,238,211,140,248,156,164,0,202,186,215,135,60,12,63,63,99,104,143,165,98,135,254,62,124,178,207,69,44,8,207,229,84,164,46,250,213,146,3,251,248,240,52,57,162,240,188,232,109,11,131,79,70,235,77,141,234,204,131,31,94,52,138,198,205,182,90,189,117,91,98,82,41,17,136,53,255,189,95,241,236,88,221,141,145,204,0,27,132,126,232,164,133,14,197,9,138,114,28,138,43,204,12]}}},"time":1467474291566,"req_id":"e7284dcf488afcb4e14c","level":"trace","message":"sending error xml response","hostname":"libbbqconn01.local","pid":72}
{"name":"S3","accessKey":"6XCJ7R7FUT9UYQJ6DC0Y","errorMessage":{"code":"ECONNRESET"},"time":1467474291680,"req_id":"e7284dcf488afcb4e14c","level":"error","message":"received error message from vault","hostname":"libbbqconn01.local","pid":72}
{"name":"S3","accessKey":"6XCJ7R7FUT9UYQJ6DC0Y","error":{"code":"ECONNRESET"},"time":1467474291681,"req_id":"e7284dcf488afcb4e14c","level":"warn","message":"authentication error","hostname":"libbbqconn01.local","pid":72}
{"name":"S3","accessKey":"6XCJ7R7FUT9UYQJ6DC0Y","clientIP":"::ffff:10.241.127.20","clientPort":45347,"httpMethod":"GET","httpURL":"/","httpCode":"ECONNRESET","time":1467474291683,"req_id":"e7284dcf488afcb4e14c","elapsed_ms":166.049623,"level":"info","message":"responded with error XML","hostname":"libbbqconn01.local","pid":72}
{"name":"S3","workerId":6,"level":"error","message":"worker disconnected. making sure exits","hostname":"libbbqconn01.local","pid":42}
{"name":"S3","workerId":6,"level":"error","message":"worker exited.","hostname":"libbbqconn01.local","pid":42}
{"name":"S3","workerId":12,"level":"error","message":"new worker forked","hostname":"libbbqconn01.local","pid":42}
{"name":"S3","host":"lb1bbqconn01.local","port":8500,"https":true,"level":"info","message":"vaultclient configuration","hostname":"libbbqconn01.local","pid":115}
{"name":"S3","bootstrap":["lb1bbqconn01.local"],"https":true,"level":"info","message":"bucketclient configuration","hostname":"libbbqconn01.local","pid":115}
{"name":"S3","https":true,"level":"info","message":"Https server configuration","hostname":"libbbqconn01.local","pid":115}
{"name":"S3","address":"::","port":8000,"pid":115,"level":"info","message":"server started","hostname":"libbbqconn01.local"}
```

**Comment by LaurenSpiegel** [comment]
When creating your certificate, please try: *.yourhostname.local

The relevant error is: "Host: lb1bbqconn01.local. is not cert's CN: *.local"

This error is being returned by Vault's server and is causing S3 to crash since the error is not being converted to a proper arsenal error.

**Comment by dkilcy** [comment]
My hostname convention is:
proxy1.local for HAproxy and conn1 thru conn5.local
What should I use for the CN for the cert and CA cert?

I can change the hostname convention if there is a combo that will work....

**Comment by dkilcy** [comment]
It was a problem with my CN.  Closing.
