### ISSUE TITLE
npm fails to install

### ISSUE THREAD

**Issue by manutalcual** [scality/S3#885]
# Description

I'm trying to install S3 into a linux container (not Docker, but LXC) and running git clone, and npm install from the provisioning script, but it fails.

### Steps to reproduce the issue

sudo lxc-create -n s3 -t my-template

My template actually:
```
    mkdir $rootfs/home/ubuntu/.ssh/
    ssh-keyscan github.com 2>/dev/nul > $rootfs/home/ubuntu/.ssh/known_hosts
    chmod 600 $rootfs/home/ubuntu/.ssh/known_hosts
    cat <<'EOF' > $rootfs/home/ubuntu/s3.sh
#!/bin/sh

chown -R ubuntu. /home/ubuntu/.ssh
cd /home/ubuntu
git clone https://github.com/scality/S3.git
chown -R ubuntu. /home/ubuntu/S3
su - ubuntu -c "cd S3; npm install"

# Return 0 no matter what so the container gets created
exit 0

EOF

    chroot $rootfs chmod 755 /home/ubuntu/s3.sh
    chroot $rootfs /home/ubuntu/s3.sh $1
```

And it fails in the ```su - ubuntu -c "cd S3; npm install"```

### Actual result

```
npm ERR! git clone --template=/home/ubuntu/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /home/ubuntu/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719: Cloning into bare repository '/home/ubuntu/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719'...
npm ERR! git clone --template=/home/ubuntu/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /home/ubuntu/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719: Permission denied (publickey).
npm ERR! git clone --template=/home/ubuntu/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /home/ubuntu/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719: fatal: Could not read from remote repository.
npm ERR! git clone --template=/home/ubuntu/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /home/ubuntu/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719: 
npm ERR! git clone --template=/home/ubuntu/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /home/ubuntu/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719: Please make sure you have the correct access rights
npm ERR! git clone --template=/home/ubuntu/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /home/ubuntu/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719: and the repository exists.
npm WARN optional Skipping failed optional dependency //cdmiclient:
npm WARN Command failed: git clone --template=/home/ubuntu/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /home/ubuntu/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719
npm WARN Cloning into bare repository '/home/ubuntu/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719'...
npm WARN Permission denied (publickey).
npm WARN fatal: Could not read from remote repository.
npm WARN 
npm WARN Please make sure you have the correct access rights
npm WARN and the repository exists.
npm WARN 
npm WARN eslint-config-airbnb@6.2.0 requires a peer of eslint-plugin-react@^4.2.3 but none was installed.
```

After this happens, when I try to run npm start it fails:

```
ubuntu@s3:~/S3$ npm start

> s3@7.0.0 start /home/ubuntu/S3
> npm-run-all --parallel start_dmd start_s3server


> s3@7.0.0 start_dmd /home/ubuntu/S3
> npm-run-all --parallel start_mdserver start_dataserver


> s3@7.0.0 start_s3server /home/ubuntu/S3
> node index.js

/home/ubuntu/S3/lib/server.js:7
const { internalHandlers } = require('./utilities/internalHandlers');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/S3/index.js:3:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

npm ERR! Linux 4.10.0-33-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/share/npm/bin/npm-cli.js" "run" "start_s3server"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! s3@7.0.0 start_s3server: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the s3@7.0.0 start_s3server script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the s3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs s3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls s3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/S3/npm-debug.log
ERROR: "start_s3server" exited with 1.

npm ERR! Linux 4.10.0-33-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! s3@7.0.0 start: `npm-run-all --parallel start_dmd start_s3server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the s3@7.0.0 start script 'npm-run-all --parallel start_dmd start_s3server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the s3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all --parallel start_dmd start_s3server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs s3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls s3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/S3/npm-debug.log
```

### Additional data

/home/ubuntu/S3/npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle s3@7.0.0~prestart: s3@7.0.0
6 silly lifecycle s3@7.0.0~prestart: no script for prestart, continuing
7 info lifecycle s3@7.0.0~start: s3@7.0.0
8 verbose lifecycle s3@7.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle s3@7.0.0~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/ubuntu/S3/node_modules/.bin:/home/ubuntu/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle s3@7.0.0~start: CWD: /home/ubuntu/S3
11 silly lifecycle s3@7.0.0~start: Args: [ '-c', 'npm-run-all --parallel start_dmd start_s3server' ]
12 silly lifecycle s3@7.0.0~start: Returned: code: 1  signal: null
13 info lifecycle s3@7.0.0~start: Failed to exec start script
14 verbose stack Error: s3@7.0.0 start: `npm-run-all --parallel start_dmd start_s3server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid s3@7.0.0
16 verbose cwd /home/ubuntu/S3
17 error Linux 4.10.0-33-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error s3@7.0.0 start: `npm-run-all --parallel start_dmd start_s3server`
22 error Exit status 1
23 error Failed at the s3@7.0.0 start script 'npm-run-all --parallel start_dmd start_s3server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the s3 package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm-run-all --parallel start_dmd start_s3server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs s3
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls s3
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
### Installed packages

build-essential
git-core
wget
nodejs
nodejs-legacy
npm
python
python-setuptools

### Expected result

I've installed this in my machine, just to test the process before making it into a script and it worked just fine.
I see the git clone errors, but I don't understand why there are errors as I'm running everything just like in my machine.
Could you give a clue or a solution?

### Additional information:

Ubuntu 16.04.3 LTS (Xenial Xerus)
Node.js v4.2.6
npm 3.5.2

**Comment by manutalcual** [comment]
I see now my Node.js version isn't the required one. I'm going to test with newer one.

**Comment by manutalcual** [comment]
Yes. That was the problem.

Sorry for the inconveniences.
