### ISSUE TITLE
"npm install" fail, what is that i am missing

### ISSUE THREAD

**Issue by Mo33n** [scality/S3#947]
```
[root@ivr S3]# CC=/opt/rh/devtoolset-2/root/usr/bin/gcc CXX=/opt/rh/devtoolset-2/root/usr/bin/g++ npm install
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /root/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719: Initialized empty Git repository in /root/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719/
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /root/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719:
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /root/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719: Permission denied (publickey).
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /root/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719: fatal: The remote end hung up unexpectedly
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> diskusage@0.2.4 install /home/cloudStorage/S3/node_modules/diskusage
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.11.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/cloudStorage/S3/node_modules/diskusage/.node-gyp"
Traceback (most recent call last):
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2775, in Load
    variables, includes, depth, check, True)
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
    includes, True, check)
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 243, in LoadOneBuildFile
    None)
  File "binding.gyp", line 1
    {
     ^
SyntaxError: invalid syntax
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 2.6.32-696.6.3.el6.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/cloudStorage/S3/node_modules/diskusage
gyp ERR! node -v v6.11.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
s3@7.0.0 /home/cloudStorage/S3
├─┬ async@2.5.0
│ └── lodash@4.17.4
├─┬ aws-sdk@2.28.0
│ ├─┬ buffer@4.9.1
│ │ ├── base64-js@1.2.1
│ │ ├── ieee754@1.1.8
│ │ └── isarray@1.0.0
│ ├── crypto-browserify@1.0.9
│ ├── jmespath@0.15.0
│ ├── querystring@0.2.0
│ ├── sax@1.1.5
│ ├─┬ url@0.10.3
│ │ └── punycode@1.3.2
│ ├── uuid@3.0.0
│ ├── xml2js@0.4.15
│ └─┬ xmlbuilder@2.6.2
│   └── lodash@3.5.0
├─┬ azure-storage@2.6.0
│ ├── browserify-mime@1.2.9
│ ├── extend@1.2.1
│ ├─┬ json-edm-parser@0.1.2
│ │ └── jsonparse@1.2.0
│ ├─┬ md5.js@1.3.4
│ │ └── hash-base@3.0.4
│ ├─┬ readable-stream@2.0.6
│ │ ├── core-util-is@1.0.2
│ │ ├── inherits@2.0.3
│ │ ├── isarray@1.0.0
│ │ ├── process-nextick-args@1.0.7
│ │ ├── string_decoder@0.10.31
│ │ └── util-deprecate@1.0.2
│ ├─┬ request@2.81.0
│ │ ├── aws-sign2@0.6.0
│ │ ├── aws4@1.6.0
│ │ ├── caseless@0.12.0
│ │ ├─┬ combined-stream@1.0.5
│ │ │ └── delayed-stream@1.0.0
│ │ ├── extend@3.0.1
│ │ ├── forever-agent@0.6.1
│ │ ├─┬ form-data@2.1.4
│ │ │ └── asynckit@0.4.0
│ │ ├─┬ har-validator@4.2.1
│ │ │ └── har-schema@1.0.5
│ │ ├─┬ hawk@3.1.3
│ │ │ ├── boom@2.10.1
│ │ │ ├── cryptiles@2.0.5
│ │ │ ├── hoek@2.16.3
│ │ │ └── sntp@1.0.9
│ │ ├─┬ http-signature@1.1.1
│ │ │ ├── assert-plus@0.2.0
│ │ │ ├─┬ jsprim@1.4.1
│ │ │ │ ├── assert-plus@1.0.0
│ │ │ │ ├── extsprintf@1.3.0
│ │ │ │ ├── json-schema@0.2.3
│ │ │ │ └─┬ verror@1.10.0
│ │ │ │   └── assert-plus@1.0.0
│ │ │ └─┬ sshpk@1.13.1
│ │ │   ├── assert-plus@1.0.0
│ │ │   ├── bcrypt-pbkdf@1.0.1
│ │ │   ├─┬ dashdash@1.14.1
│ │ │   │ └── assert-plus@1.0.0
│ │ │   ├── ecc-jsbn@0.1.1
│ │ │   ├─┬ getpass@0.1.7
│ │ │   │ └── assert-plus@1.0.0
│ │ │   ├── jsbn@0.1.1
│ │ │   └── tweetnacl@0.14.5
│ │ ├── is-typedarray@1.0.0
│ │ ├── isstream@0.1.2
│ │ ├── json-stringify-safe@5.0.1
│ │ ├─┬ mime-types@2.1.17
│ │ │ └── mime-db@1.30.0
│ │ ├── oauth-sign@0.8.2
│ │ ├── performance-now@0.2.0
│ │ ├── qs@6.4.0
│ │ ├── safe-buffer@5.1.1
│ │ ├── stringstream@0.0.5
│ │ ├─┬ tough-cookie@2.3.3
│ │ │ └── punycode@1.4.1
│ │ ├── tunnel-agent@0.6.0
│ │ └── uuid@3.1.0
│ ├── underscore@1.8.3
│ ├── uuid@3.1.0
│ ├── validator@3.35.0
│ ├─┬ xml2js@0.2.7
│ │ └── sax@0.5.2
│ └── xmlbuilder@0.4.3
├── bluebird@3.5.1
├── bucketclient@7.0.0  (git://github.com/scality/bucketclient.git#8d47428289bca2b5b885ac13b6a5f7ed781d906e)
├── commander@2.11.0
├─┬ eslint@2.13.1
│ ├─┬ chalk@1.1.3
│ │ ├── ansi-styles@2.2.1
│ │ ├── escape-string-regexp@1.0.5
│ │ ├── has-ansi@2.0.0
│ │ ├── strip-ansi@3.0.1
│ │ └── supports-color@2.0.0
│ ├─┬ concat-stream@1.6.0
│ │ ├─┬ readable-stream@2.3.3
│ │ │ ├── isarray@1.0.0
│ │ │ └── string_decoder@1.0.3
│ │ └── typedarray@0.0.6
│ ├─┬ debug@2.3.3
│ │ └── ms@0.7.2
│ ├─┬ doctrine@1.5.0
│ │ └── isarray@1.0.0
│ ├─┬ es6-map@0.1.5
│ │ ├── d@1.0.0
│ │ ├── es5-ext@0.10.35
│ │ ├── es6-iterator@2.0.3
│ │ ├── es6-set@0.1.5
│ │ ├── es6-symbol@3.1.1
│ │ └── event-emitter@0.3.5
│ ├─┬ escope@3.6.0
│ │ ├── es6-weak-map@2.0.2
│ │ └── esrecurse@4.2.0
│ ├─┬ espree@3.5.1
│ │ ├── acorn@5.1.2
│ │ └─┬ acorn-jsx@3.0.1
│ │   └── acorn@3.3.0
│ ├── estraverse@4.2.0
│ ├── esutils@2.0.2
│ ├─┬ file-entry-cache@1.3.1
│ │ ├─┬ flat-cache@1.3.0
│ │ │ ├── circular-json@0.3.3
│ │ │ ├─┬ del@2.2.2
│ │ │ │ ├─┬ globby@5.0.0
│ │ │ │ │ ├─┬ array-union@1.0.2
│ │ │ │ │ │ └── array-uniq@1.0.3
│ │ │ │ │ └── arrify@1.0.1
│ │ │ │ ├── is-path-cwd@1.0.0
│ │ │ │ ├─┬ is-path-in-cwd@1.0.0
│ │ │ │ │ └── is-path-inside@1.0.0
│ │ │ │ └─┬ pinkie-promise@2.0.1
│ │ │ │   └── pinkie@2.0.4
│ │ │ ├── graceful-fs@4.1.11
│ │ │ └── write@0.2.1
│ │ └── object-assign@4.1.1
│ ├─┬ glob@7.1.2
│ │ ├── fs.realpath@1.0.0
│ │ └── inflight@1.0.6
│ ├── globals@9.18.0
│ ├── ignore@3.3.5
│ ├── imurmurhash@0.1.4
│ ├─┬ inquirer@0.12.0
│ │ ├── ansi-escapes@1.4.0
│ │ ├── ansi-regex@2.1.1
│ │ ├─┬ cli-cursor@1.0.2
│ │ │ └─┬ restore-cursor@1.0.1
│ │ │   ├── exit-hook@1.1.1
│ │ │   └── onetime@1.1.0
│ │ ├── cli-width@2.2.0
│ │ ├── figures@1.7.0
│ │ ├─┬ readline2@1.0.1
│ │ │ ├── code-point-at@1.1.0
│ │ │ ├─┬ is-fullwidth-code-point@1.0.0
│ │ │ │ └── number-is-nan@1.0.1
│ │ │ └── mute-stream@0.0.5
│ │ ├── run-async@0.1.0
│ │ ├── rx-lite@3.1.2
│ │ ├── string-width@1.0.2
│ │ └── through@2.3.8
│ ├─┬ is-my-json-valid@2.16.1
│ │ ├── generate-function@2.0.0
│ │ ├─┬ generate-object-property@1.2.0
│ │ │ └── is-property@1.0.2
│ │ ├── jsonpointer@4.0.1
│ │ └── xtend@4.0.1
│ ├─┬ is-resolvable@1.0.0
│ │ └── tryit@1.0.3
│ ├─┬ js-yaml@3.10.0
│ │ ├─┬ argparse@1.0.9
│ │ │ └── sprintf-js@1.0.3
│ │ └── esprima@4.0.0
│ ├─┬ json-stable-stringify@1.0.1
│ │ └── jsonify@0.0.0
│ ├─┬ levn@0.3.0
│ │ ├── prelude-ls@1.1.2
│ │ └── type-check@0.3.2
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├─┬ optionator@0.8.2
│ │ ├── deep-is@0.1.3
│ │ └── fast-levenshtein@2.0.6
│ ├── path-is-absolute@1.0.1
│ ├── path-is-inside@1.0.2
│ ├── pluralize@1.2.1
│ ├── progress@1.1.8
│ ├─┬ require-uncached@1.0.3
│ │ ├─┬ caller-path@0.1.0
│ │ │ └── callsites@0.2.0
│ │ └── resolve-from@1.0.1
│ ├── shelljs@0.6.1
│ ├── strip-json-comments@1.0.4
│ ├─┬ table@3.8.3
│ │ ├─┬ ajv@4.10.0
│ │ │ └── co@4.6.0
│ │ ├── ajv-keywords@1.5.1
│ │ ├── slice-ansi@0.0.4
│ │ └─┬ string-width@2.1.1
│ │   ├── is-fullwidth-code-point@2.0.0
│ │   └─┬ strip-ansi@4.0.0
│ │     └── ansi-regex@3.0.0
│ ├── text-table@0.2.0
│ └─┬ user-home@2.0.0
│   └── os-homedir@1.0.2
├── eslint-config-airbnb@6.2.0
├─┬ eslint-config-scality@1.1.0  (git://github.com/scality/Guidelines.git#561ab2fef1da33378f1948d6e7a65d8ba74d0136)
│ ├─┬ commander@1.3.2
│ │ └── keypress@0.1.0
│ └─┬ markdownlint@0.0.8
│   └─┬ markdown-it@4.4.0
│     ├── entities@1.1.1
│     ├── linkify-it@1.2.4
│     ├── mdurl@1.0.1
│     └── uc.micro@1.0.3
├── UNMET PEER DEPENDENCY eslint-plugin-react@^4.2.3
├─┬ ioredis@2.4.0
│ ├── cluster-key-slot@1.0.8
│ ├── double-ended-queue@2.1.0-0
│ ├── flexbuffer@0.0.6
│ ├── redis-commands@1.3.1
│ └── redis-parser@1.3.0
├─┬ istanbul@1.0.0-alpha.2
│ ├── abbrev@1.0.9
│ ├── async@1.5.2
│ ├── nopt@3.0.6
│ ├─┬ which@1.3.0
│ │ └── isexe@2.0.0
│ └── wordwrap@1.0.0
├─┬ istanbul-api@1.0.0-alpha.13
│ ├── async@1.5.2
│ ├─┬ fileset@0.2.1
│ │ ├── glob@5.0.15
│ │ └── minimatch@2.0.10
│ ├── istanbul-lib-coverage@1.1.1
│ ├─┬ istanbul-lib-hook@1.0.7
│ │ └─┬ append-transform@0.4.0
│ │   └─┬ default-require-extensions@1.0.0
│ │     └─┬ strip-bom@2.0.0
│ │       └── is-utf8@0.2.1
│ ├─┬ istanbul-lib-instrument@1.8.0
│ │ ├─┬ babel-generator@6.26.0
│ │ │ ├── babel-messages@6.23.0
│ │ │ ├─┬ babel-runtime@6.26.0
│ │ │ │ ├── core-js@2.5.1
│ │ │ │ └── regenerator-runtime@0.11.0
│ │ │ ├─┬ detect-indent@4.0.0
│ │ │ │ └─┬ repeating@2.0.1
│ │ │ │   └── is-finite@1.0.2
│ │ │ ├── jsesc@1.3.0
│ │ │ └── trim-right@1.0.1
│ │ ├── babel-template@6.26.0
│ │ ├─┬ babel-traverse@6.26.0
│ │ │ ├─┬ babel-code-frame@6.26.0
│ │ │ │ └── js-tokens@3.0.2
│ │ │ ├─┬ debug@2.6.9
│ │ │ │ └── ms@2.0.0
│ │ │ └─┬ invariant@2.2.2
│ │ │   └── loose-envify@1.3.1
│ │ ├─┬ babel-types@6.26.0
│ │ │ └── to-fast-properties@1.0.3
│ │ ├── babylon@6.18.0
│ │ └── semver@5.4.1
│ ├─┬ istanbul-lib-report@1.1.1
│ │ ├── path-parse@1.0.5
│ │ └─┬ supports-color@3.2.3
│ │   └── has-flag@1.0.0
│ ├─┬ istanbul-lib-source-maps@1.2.1
│ │ ├─┬ debug@2.6.9
│ │ │ └── ms@2.0.0
│ │ ├── rimraf@2.6.2
│ │ └── source-map@0.5.7
│ ├─┬ istanbul-reports@1.1.2
│ │ └─┬ handlebars@4.0.11
│ │   ├── async@1.5.2
│ │   ├─┬ optimist@0.6.1
│ │   │ ├── minimist@0.0.10
│ │   │ └── wordwrap@0.0.3
│ │   ├─┬ source-map@0.4.4
│ │   │ └── amdefine@1.0.1
│ │   └─┬ uglify-js@2.8.29
│ │     ├── uglify-to-browserify@1.0.2
│ │     └─┬ yargs@3.10.0
│ │       ├── camelcase@1.2.1
│ │       ├─┬ cliui@2.1.0
│ │       │ ├─┬ center-align@0.1.3
│ │       │ │ ├─┬ align-text@0.1.4
│ │       │ │ │ ├── kind-of@3.2.2
│ │       │ │ │ ├── longest@1.0.1
│ │       │ │ │ └── repeat-string@1.6.1
│ │       │ │ └── lazy-cache@1.0.4
│ │       │ ├── right-align@0.1.3
│ │       │ └── wordwrap@0.0.2
│ │       ├── decamelize@1.2.0
│ │       └── window-size@0.1.0
│ └─┬ once@1.4.0
│   └── wrappy@1.0.2
├── lolex@1.6.0
├─┬ mocha@2.5.3
│ ├── commander@2.3.0
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── diff@1.4.0
│ ├── escape-string-regexp@1.0.2
│ ├─┬ glob@3.2.11
│ │ └─┬ minimatch@0.3.0
│ │   ├── lru-cache@2.7.3
│ │   └── sigmund@1.0.1
│ ├── growl@1.9.2
│ ├─┬ jade@0.26.3
│ │ ├── commander@0.6.1
│ │ └── mkdirp@0.3.0
│ ├── supports-color@1.2.0
│ └── to-iso-string@0.0.2
├─┬ mocha-junit-reporter@1.11.1
│ ├─┬ md5@2.2.1
│ │ ├── charenc@0.0.2
│ │ ├── crypt@0.0.2
│ │ └── is-buffer@1.1.5
│ └── xml@1.0.1
├─┬ node-mocks-http@1.6.6
│ ├─┬ accepts@1.3.3
│ │ └── negotiator@0.6.1
│ ├── depd@1.1.1
│ ├── fresh@0.5.2
│ ├── merge-descriptors@1.0.1
│ ├── methods@1.1.2
│ ├── mime@1.4.1
│ ├── net@1.0.2
│ ├── parseurl@1.3.2
│ ├── range-parser@1.2.0
│ └─┬ type-is@1.6.15
│   └── media-typer@0.3.0
├── node-uuid@1.4.8
├─┬ npm-run-all@4.0.2
│ ├─┬ cross-spawn@5.1.0
│ │ ├─┬ lru-cache@4.1.1
│ │ │ ├── pseudomap@1.0.2
│ │ │ └── yallist@2.1.2
│ │ └─┬ shebang-command@1.2.0
│ │   └── shebang-regex@1.0.0
│ ├─┬ minimatch@3.0.4
│ │ └─┬ brace-expansion@1.1.8
│ │   ├── balanced-match@1.0.0
│ │   └── concat-map@0.0.1
│ ├─┬ ps-tree@1.1.0
│ │ └─┬ event-stream@3.3.4
│ │   ├── duplexer@0.1.1
│ │   ├── from@0.1.7
│ │   ├── map-stream@0.1.0
│ │   ├── pause-stream@0.0.11
│ │   ├── split@0.3.3
│ │   └── stream-combiner@0.0.4
│ ├─┬ read-pkg@2.0.0
│ │ ├─┬ load-json-file@2.0.0
│ │ │ ├─┬ parse-json@2.2.0
│ │ │ │ └─┬ error-ex@1.3.1
│ │ │ │   └── is-arrayish@0.2.1
│ │ │ ├── pify@2.3.0
│ │ │ └── strip-bom@3.0.0
│ │ ├─┬ normalize-package-data@2.4.0
│ │ │ ├── hosted-git-info@2.5.0
│ │ │ ├─┬ is-builtin-module@1.0.0
│ │ │ │ └── builtin-modules@1.1.1
│ │ │ └─┬ validate-npm-package-license@3.0.1
│ │ │   ├─┬ spdx-correct@1.0.2
│ │ │   │ └── spdx-license-ids@1.2.2
│ │ │   └── spdx-expression-parse@1.0.4
│ │ └── path-type@2.0.0
│ ├─┬ shell-quote@1.6.1
│ │ ├── array-filter@0.0.1
│ │ ├── array-map@0.0.0
│ │ └── array-reduce@0.0.0
│ └─┬ string.prototype.padend@3.0.0
│   ├─┬ define-properties@1.1.2
│   │ ├── foreach@2.0.5
│   │ └── object-keys@1.0.11
│   ├─┬ es-abstract@1.9.0
│   │ ├─┬ es-to-primitive@1.1.1
│   │ │ ├── is-date-object@1.0.1
│   │ │ └── is-symbol@1.0.1
│   │ ├── has@1.0.1
│   │ ├── is-callable@1.1.3
│   │ └── is-regex@1.0.4
│   └── function-bind@1.1.1
├─┬ s3blaster@0.0.1  (git://github.com/scality/s3blaster.git#6417f8379201c8d25558b25a26cea5c3ef1c5d78)
│ ├── async@1.4.2
│ ├── generic-pool@2.5.4
│ ├── readline-sync@1.4.7
│ └─┬ ssh2@0.5.5
│   └─┬ ssh2-streams@0.1.20
│     ├── asn1@0.2.3
│     └── streamsearch@0.1.2
├── sproxydclient@7.0.0  (git://github.com/scality/sproxydclient.git#10e6ce918ce31d8f62122f247cae70698aed7e26)
├── tv4@1.3.0
├── utf8@2.1.2
├─┬ werelogs@7.0.0  (git://github.com/scality/werelogs.git#ea2168a79a2eaa0a7c785e32a33884759edce3bb)
│ └── safe-json-stringify@1.0.4
└─┬ xml2js@0.4.19
  ├── sax@1.2.4
  └── xmlbuilder@9.0.4

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cdmiclient@github:scality/cdmiclient (node_modules/cdmiclient):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /root/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Permission denied (publickey).
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fatal: The remote end hung up unexpectedly
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:
npm WARN eslint-config-airbnb@6.2.0 requires a peer of eslint-plugin-react@^4.2.3 but none was installed.
npm ERR! Linux 2.6.32-696.6.3.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! diskusage@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the diskusage@0.2.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the diskusage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs diskusage
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls diskusage
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cloudStorage/S3/npm-debug.log

```

**Comment by ThibaultRiviere** [comment]
@Mo33n  Can you provide the result of the command, `node --version`

**Comment by LaurenSpiegel** [comment]
Can you try it not as root?
