### ISSUE TITLE
Stringify error

### ISSUE THREAD

**Issue by hbbio** [scality/S3#95]
I cloned the repository, and ran successfully `npm install` (after installing `g++` which was initially missing).

But, I can't run the server using `npm start` because of the following error:

```
Error: Cannot find module 'core-js/library/fn/json/stringify'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/henri/git/S3/node_modules/babel-core/node_modules/babel-runtime/core-js/json/stringify.js:1:93)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

I'm using Node 4.4.6. Could this be the reason?

**Comment by nicolas2bert** [comment]
Hey @hbbio ,
Which npm version are you using?

Nicolas

**Comment by hbbio** [comment]
I'm using npm 2.15.5 and node

**Comment by nicolas2bert** [comment]
Check our Dependencies section here : https://github.com/scality/S3#dependencies

> npm 2.7 or greater is required.

Update it and let me know,

Nicolas

**Comment by hbbio** [comment]
It seems that npm 2.15 > 2.7.

Problem has been solved like in this thread: https://github.com/babel/gulp-babel/issues/50 so it may be a npm bug.
